using NUnit.Framework;
using System.Collections.Generic;
using System.Linq;

namespace ChessDotNet.Tests
{
    [TestFixture]
    public static class Chess960PositionTests
    {
        static Dictionary<int, string> startArrays = new Dictionary<int, string>()
        {
            { 000, "BBQNNRKR" },
            { 001, "BQNBNRKR" },
            { 002, "BQNNRBKR" },
            { 003, "BQNNRKRB" },
            { 004, "QBBNNRKR" },
            { 005, "QNBBNRKR" },
            { 006, "QNBNRBKR" },
            { 007, "QNBNRKRB" },
            { 008, "QBNNBRKR" },
            { 009, "QNNBBRKR" },
            { 010, "QNNRBBKR" },
            { 011, "QNNRBKRB" },
            { 012, "QBNNRKBR" },
            { 013, "QNNBRKBR" },
            { 014, "QNNRKBBR" },
            { 015, "QNNRKRBB" },
            { 016, "BBNQNRKR" },
            { 017, "BNQBNRKR" },
            { 018, "BNQNRBKR" },
            { 019, "BNQNRKRB" },
            { 020, "NBBQNRKR" },
            { 021, "NQBBNRKR" },
            { 022, "NQBNRBKR" },
            { 023, "NQBNRKRB" },
            { 024, "NBQNBRKR" },
            { 025, "NQNBBRKR" },
            { 026, "NQNRBBKR" },
            { 027, "NQNRBKRB" },
            { 028, "NBQNRKBR" },
            { 029, "NQNBRKBR" },
            { 030, "NQNRKBBR" },
            { 031, "NQNRKRBB" },
            { 032, "BBNNQRKR" },
            { 033, "BNNBQRKR" },
            { 034, "BNNQRBKR" },
            { 035, "BNNQRKRB" },
            { 036, "NBBNQRKR" },
            { 037, "NNBBQRKR" },
            { 038, "NNBQRBKR" },
            { 039, "NNBQRKRB" },
            { 040, "NBNQBRKR" },
            { 041, "NNQBBRKR" },
            { 042, "NNQRBBKR" },
            { 043, "NNQRBKRB" },
            { 044, "NBNQRKBR" },
            { 045, "NNQBRKBR" },
            { 046, "NNQRKBBR" },
            { 047, "NNQRKRBB" },
            { 048, "BBNNRQKR" },
            { 049, "BNNBRQKR" },
            { 050, "BNNRQBKR" },
            { 051, "BNNRQKRB" },
            { 052, "NBBNRQKR" },
            { 053, "NNBBRQKR" },
            { 054, "NNBRQBKR" },
            { 055, "NNBRQKRB" },
            { 056, "NBNRBQKR" },
            { 057, "NNRBBQKR" },
            { 058, "NNRQBBKR" },
            { 059, "NNRQBKRB" },
            { 060, "NBNRQKBR" },
            { 061, "NNRBQKBR" },
            { 062, "NNRQKBBR" },
            { 063, "NNRQKRBB" },
            { 064, "BBNNRKQR" },
            { 065, "BNNBRKQR" },
            { 066, "BNNRKBQR" },
            { 067, "BNNRKQRB" },
            { 068, "NBBNRKQR" },
            { 069, "NNBBRKQR" },
            { 070, "NNBRKBQR" },
            { 071, "NNBRKQRB" },
            { 072, "NBNRBKQR" },
            { 073, "NNRBBKQR" },
            { 074, "NNRKBBQR" },
            { 075, "NNRKBQRB" },
            { 076, "NBNRKQBR" },
            { 077, "NNRBKQBR" },
            { 078, "NNRKQBBR" },
            { 079, "NNRKQRBB" },
            { 080, "BBNNRKRQ" },
            { 081, "BNNBRKRQ" },
            { 082, "BNNRKBRQ" },
            { 083, "BNNRKRQB" },
            { 084, "NBBNRKRQ" },
            { 085, "NNBBRKRQ" },
            { 086, "NNBRKBRQ" },
            { 087, "NNBRKRQB" },
            { 088, "NBNRBKRQ" },
            { 089, "NNRBBKRQ" },
            { 090, "NNRKBBRQ" },
            { 091, "NNRKBRQB" },
            { 092, "NBNRKRBQ" },
            { 093, "NNRBKRBQ" },
            { 094, "NNRKRBBQ" },
            { 095, "NNRKRQBB" },
            { 096, "BBQNRNKR" },
            { 097, "BQNBRNKR" },
            { 098, "BQNRNBKR" },
            { 099, "BQNRNKRB" },
            { 100, "QBBNRNKR" },
            { 101, "QNBBRNKR" },
            { 102, "QNBRNBKR" },
            { 103, "QNBRNKRB" },
            { 104, "QBNRBNKR" },
            { 105, "QNRBBNKR" },
            { 106, "QNRNBBKR" },
            { 107, "QNRNBKRB" },
            { 108, "QBNRNKBR" },
            { 109, "QNRBNKBR" },
            { 110, "QNRNKBBR" },
            { 111, "QNRNKRBB" },
            { 112, "BBNQRNKR" },
            { 113, "BNQBRNKR" },
            { 114, "BNQRNBKR" },
            { 115, "BNQRNKRB" },
            { 116, "NBBQRNKR" },
            { 117, "NQBBRNKR" },
            { 118, "NQBRNBKR" },
            { 119, "NQBRNKRB" },
            { 120, "NBQRBNKR" },
            { 121, "NQRBBNKR" },
            { 122, "NQRNBBKR" },
            { 123, "NQRNBKRB" },
            { 124, "NBQRNKBR" },
            { 125, "NQRBNKBR" },
            { 126, "NQRNKBBR" },
            { 127, "NQRNKRBB" },
            { 128, "BBNRQNKR" },
            { 129, "BNRBQNKR" },
            { 130, "BNRQNBKR" },
            { 131, "BNRQNKRB" },
            { 132, "NBBRQNKR" },
            { 133, "NRBBQNKR" },
            { 134, "NRBQNBKR" },
            { 135, "NRBQNKRB" },
            { 136, "NBRQBNKR" },
            { 137, "NRQBBNKR" },
            { 138, "NRQNBBKR" },
            { 139, "NRQNBKRB" },
            { 140, "NBRQNKBR" },
            { 141, "NRQBNKBR" },
            { 142, "NRQNKBBR" },
            { 143, "NRQNKRBB" },
            { 144, "BBNRNQKR" },
            { 145, "BNRBNQKR" },
            { 146, "BNRNQBKR" },
            { 147, "BNRNQKRB" },
            { 148, "NBBRNQKR" },
            { 149, "NRBBNQKR" },
            { 150, "NRBNQBKR" },
            { 151, "NRBNQKRB" },
            { 152, "NBRNBQKR" },
            { 153, "NRNBBQKR" },
            { 154, "NRNQBBKR" },
            { 155, "NRNQBKRB" },
            { 156, "NBRNQKBR" },
            { 157, "NRNBQKBR" },
            { 158, "NRNQKBBR" },
            { 159, "NRNQKRBB" },
            { 160, "BBNRNKQR" },
            { 161, "BNRBNKQR" },
            { 162, "BNRNKBQR" },
            { 163, "BNRNKQRB" },
            { 164, "NBBRNKQR" },
            { 165, "NRBBNKQR" },
            { 166, "NRBNKBQR" },
            { 167, "NRBNKQRB" },
            { 168, "NBRNBKQR" },
            { 169, "NRNBBKQR" },
            { 170, "NRNKBBQR" },
            { 171, "NRNKBQRB" },
            { 172, "NBRNKQBR" },
            { 173, "NRNBKQBR" },
            { 174, "NRNKQBBR" },
            { 175, "NRNKQRBB" },
            { 176, "BBNRNKRQ" },
            { 177, "BNRBNKRQ" },
            { 178, "BNRNKBRQ" },
            { 179, "BNRNKRQB" },
            { 180, "NBBRNKRQ" },
            { 181, "NRBBNKRQ" },
            { 182, "NRBNKBRQ" },
            { 183, "NRBNKRQB" },
            { 184, "NBRNBKRQ" },
            { 185, "NRNBBKRQ" },
            { 186, "NRNKBBRQ" },
            { 187, "NRNKBRQB" },
            { 188, "NBRNKRBQ" },
            { 189, "NRNBKRBQ" },
            { 190, "NRNKRBBQ" },
            { 191, "NRNKRQBB" },
            { 192, "BBQNRKNR" },
            { 193, "BQNBRKNR" },
            { 194, "BQNRKBNR" },
            { 195, "BQNRKNRB" },
            { 196, "QBBNRKNR" },
            { 197, "QNBBRKNR" },
            { 198, "QNBRKBNR" },
            { 199, "QNBRKNRB" },
            { 200, "QBNRBKNR" },
            { 201, "QNRBBKNR" },
            { 202, "QNRKBBNR" },
            { 203, "QNRKBNRB" },
            { 204, "QBNRKNBR" },
            { 205, "QNRBKNBR" },
            { 206, "QNRKNBBR" },
            { 207, "QNRKNRBB" },
            { 208, "BBNQRKNR" },
            { 209, "BNQBRKNR" },
            { 210, "BNQRKBNR" },
            { 211, "BNQRKNRB" },
            { 212, "NBBQRKNR" },
            { 213, "NQBBRKNR" },
            { 214, "NQBRKBNR" },
            { 215, "NQBRKNRB" },
            { 216, "NBQRBKNR" },
            { 217, "NQRBBKNR" },
            { 218, "NQRKBBNR" },
            { 219, "NQRKBNRB" },
            { 220, "NBQRKNBR" },
            { 221, "NQRBKNBR" },
            { 222, "NQRKNBBR" },
            { 223, "NQRKNRBB" },
            { 224, "BBNRQKNR" },
            { 225, "BNRBQKNR" },
            { 226, "BNRQKBNR" },
            { 227, "BNRQKNRB" },
            { 228, "NBBRQKNR" },
            { 229, "NRBBQKNR" },
            { 230, "NRBQKBNR" },
            { 231, "NRBQKNRB" },
            { 232, "NBRQBKNR" },
            { 233, "NRQBBKNR" },
            { 234, "NRQKBBNR" },
            { 235, "NRQKBNRB" },
            { 236, "NBRQKNBR" },
            { 237, "NRQBKNBR" },
            { 238, "NRQKNBBR" },
            { 239, "NRQKNRBB" },
            { 240, "BBNRKQNR" },
            { 241, "BNRBKQNR" },
            { 242, "BNRKQBNR" },
            { 243, "BNRKQNRB" },
            { 244, "NBBRKQNR" },
            { 245, "NRBBKQNR" },
            { 246, "NRBKQBNR" },
            { 247, "NRBKQNRB" },
            { 248, "NBRKBQNR" },
            { 249, "NRKBBQNR" },
            { 250, "NRKQBBNR" },
            { 251, "NRKQBNRB" },
            { 252, "NBRKQNBR" },
            { 253, "NRKBQNBR" },
            { 254, "NRKQNBBR" },
            { 255, "NRKQNRBB" },
            { 256, "BBNRKNQR" },
            { 257, "BNRBKNQR" },
            { 258, "BNRKNBQR" },
            { 259, "BNRKNQRB" },
            { 260, "NBBRKNQR" },
            { 261, "NRBBKNQR" },
            { 262, "NRBKNBQR" },
            { 263, "NRBKNQRB" },
            { 264, "NBRKBNQR" },
            { 265, "NRKBBNQR" },
            { 266, "NRKNBBQR" },
            { 267, "NRKNBQRB" },
            { 268, "NBRKNQBR" },
            { 269, "NRKBNQBR" },
            { 270, "NRKNQBBR" },
            { 271, "NRKNQRBB" },
            { 272, "BBNRKNRQ" },
            { 273, "BNRBKNRQ" },
            { 274, "BNRKNBRQ" },
            { 275, "BNRKNRQB" },
            { 276, "NBBRKNRQ" },
            { 277, "NRBBKNRQ" },
            { 278, "NRBKNBRQ" },
            { 279, "NRBKNRQB" },
            { 280, "NBRKBNRQ" },
            { 281, "NRKBBNRQ" },
            { 282, "NRKNBBRQ" },
            { 283, "NRKNBRQB" },
            { 284, "NBRKNRBQ" },
            { 285, "NRKBNRBQ" },
            { 286, "NRKNRBBQ" },
            { 287, "NRKNRQBB" },
            { 288, "BBQNRKRN" },
            { 289, "BQNBRKRN" },
            { 290, "BQNRKBRN" },
            { 291, "BQNRKRNB" },
            { 292, "QBBNRKRN" },
            { 293, "QNBBRKRN" },
            { 294, "QNBRKBRN" },
            { 295, "QNBRKRNB" },
            { 296, "QBNRBKRN" },
            { 297, "QNRBBKRN" },
            { 298, "QNRKBBRN" },
            { 299, "QNRKBRNB" },
            { 300, "QBNRKRBN" },
            { 301, "QNRBKRBN" },
            { 302, "QNRKRBBN" },
            { 303, "QNRKRNBB" },
            { 304, "BBNQRKRN" },
            { 305, "BNQBRKRN" },
            { 306, "BNQRKBRN" },
            { 307, "BNQRKRNB" },
            { 308, "NBBQRKRN" },
            { 309, "NQBBRKRN" },
            { 310, "NQBRKBRN" },
            { 311, "NQBRKRNB" },
            { 312, "NBQRBKRN" },
            { 313, "NQRBBKRN" },
            { 314, "NQRKBBRN" },
            { 315, "NQRKBRNB" },
            { 316, "NBQRKRBN" },
            { 317, "NQRBKRBN" },
            { 318, "NQRKRBBN" },
            { 319, "NQRKRNBB" },
            { 320, "BBNRQKRN" },
            { 321, "BNRBQKRN" },
            { 322, "BNRQKBRN" },
            { 323, "BNRQKRNB" },
            { 324, "NBBRQKRN" },
            { 325, "NRBBQKRN" },
            { 326, "NRBQKBRN" },
            { 327, "NRBQKRNB" },
            { 328, "NBRQBKRN" },
            { 329, "NRQBBKRN" },
            { 330, "NRQKBBRN" },
            { 331, "NRQKBRNB" },
            { 332, "NBRQKRBN" },
            { 333, "NRQBKRBN" },
            { 334, "NRQKRBBN" },
            { 335, "NRQKRNBB" },
            { 336, "BBNRKQRN" },
            { 337, "BNRBKQRN" },
            { 338, "BNRKQBRN" },
            { 339, "BNRKQRNB" },
            { 340, "NBBRKQRN" },
            { 341, "NRBBKQRN" },
            { 342, "NRBKQBRN" },
            { 343, "NRBKQRNB" },
            { 344, "NBRKBQRN" },
            { 345, "NRKBBQRN" },
            { 346, "NRKQBBRN" },
            { 347, "NRKQBRNB" },
            { 348, "NBRKQRBN" },
            { 349, "NRKBQRBN" },
            { 350, "NRKQRBBN" },
            { 351, "NRKQRNBB" },
            { 352, "BBNRKRQN" },
            { 353, "BNRBKRQN" },
            { 354, "BNRKRBQN" },
            { 355, "BNRKRQNB" },
            { 356, "NBBRKRQN" },
            { 357, "NRBBKRQN" },
            { 358, "NRBKRBQN" },
            { 359, "NRBKRQNB" },
            { 360, "NBRKBRQN" },
            { 361, "NRKBBRQN" },
            { 362, "NRKRBBQN" },
            { 363, "NRKRBQNB" },
            { 364, "NBRKRQBN" },
            { 365, "NRKBRQBN" },
            { 366, "NRKRQBBN" },
            { 367, "NRKRQNBB" },
            { 368, "BBNRKRNQ" },
            { 369, "BNRBKRNQ" },
            { 370, "BNRKRBNQ" },
            { 371, "BNRKRNQB" },
            { 372, "NBBRKRNQ" },
            { 373, "NRBBKRNQ" },
            { 374, "NRBKRBNQ" },
            { 375, "NRBKRNQB" },
            { 376, "NBRKBRNQ" },
            { 377, "NRKBBRNQ" },
            { 378, "NRKRBBNQ" },
            { 379, "NRKRBNQB" },
            { 380, "NBRKRNBQ" },
            { 381, "NRKBRNBQ" },
            { 382, "NRKRNBBQ" },
            { 383, "NRKRNQBB" },
            { 384, "BBQRNNKR" },
            { 385, "BQRBNNKR" },
            { 386, "BQRNNBKR" },
            { 387, "BQRNNKRB" },
            { 388, "QBBRNNKR" },
            { 389, "QRBBNNKR" },
            { 390, "QRBNNBKR" },
            { 391, "QRBNNKRB" },
            { 392, "QBRNBNKR" },
            { 393, "QRNBBNKR" },
            { 394, "QRNNBBKR" },
            { 395, "QRNNBKRB" },
            { 396, "QBRNNKBR" },
            { 397, "QRNBNKBR" },
            { 398, "QRNNKBBR" },
            { 399, "QRNNKRBB" },
            { 400, "BBRQNNKR" },
            { 401, "BRQBNNKR" },
            { 402, "BRQNNBKR" },
            { 403, "BRQNNKRB" },
            { 404, "RBBQNNKR" },
            { 405, "RQBBNNKR" },
            { 406, "RQBNNBKR" },
            { 407, "RQBNNKRB" },
            { 408, "RBQNBNKR" },
            { 409, "RQNBBNKR" },
            { 410, "RQNNBBKR" },
            { 411, "RQNNBKRB" },
            { 412, "RBQNNKBR" },
            { 413, "RQNBNKBR" },
            { 414, "RQNNKBBR" },
            { 415, "RQNNKRBB" },
            { 416, "BBRNQNKR" },
            { 417, "BRNBQNKR" },
            { 418, "BRNQNBKR" },
            { 419, "BRNQNKRB" },
            { 420, "RBBNQNKR" },
            { 421, "RNBBQNKR" },
            { 422, "RNBQNBKR" },
            { 423, "RNBQNKRB" },
            { 424, "RBNQBNKR" },
            { 425, "RNQBBNKR" },
            { 426, "RNQNBBKR" },
            { 427, "RNQNBKRB" },
            { 428, "RBNQNKBR" },
            { 429, "RNQBNKBR" },
            { 430, "RNQNKBBR" },
            { 431, "RNQNKRBB" },
            { 432, "BBRNNQKR" },
            { 433, "BRNBNQKR" },
            { 434, "BRNNQBKR" },
            { 435, "BRNNQKRB" },
            { 436, "RBBNNQKR" },
            { 437, "RNBBNQKR" },
            { 438, "RNBNQBKR" },
            { 439, "RNBNQKRB" },
            { 440, "RBNNBQKR" },
            { 441, "RNNBBQKR" },
            { 442, "RNNQBBKR" },
            { 443, "RNNQBKRB" },
            { 444, "RBNNQKBR" },
            { 445, "RNNBQKBR" },
            { 446, "RNNQKBBR" },
            { 447, "RNNQKRBB" },
            { 448, "BBRNNKQR" },
            { 449, "BRNBNKQR" },
            { 450, "BRNNKBQR" },
            { 451, "BRNNKQRB" },
            { 452, "RBBNNKQR" },
            { 453, "RNBBNKQR" },
            { 454, "RNBNKBQR" },
            { 455, "RNBNKQRB" },
            { 456, "RBNNBKQR" },
            { 457, "RNNBBKQR" },
            { 458, "RNNKBBQR" },
            { 459, "RNNKBQRB" },
            { 460, "RBNNKQBR" },
            { 461, "RNNBKQBR" },
            { 462, "RNNKQBBR" },
            { 463, "RNNKQRBB" },
            { 464, "BBRNNKRQ" },
            { 465, "BRNBNKRQ" },
            { 466, "BRNNKBRQ" },
            { 467, "BRNNKRQB" },
            { 468, "RBBNNKRQ" },
            { 469, "RNBBNKRQ" },
            { 470, "RNBNKBRQ" },
            { 471, "RNBNKRQB" },
            { 472, "RBNNBKRQ" },
            { 473, "RNNBBKRQ" },
            { 474, "RNNKBBRQ" },
            { 475, "RNNKBRQB" },
            { 476, "RBNNKRBQ" },
            { 477, "RNNBKRBQ" },
            { 478, "RNNKRBBQ" },
            { 479, "RNNKRQBB" },
            { 480, "BBQRNKNR" },
            { 481, "BQRBNKNR" },
            { 482, "BQRNKBNR" },
            { 483, "BQRNKNRB" },
            { 484, "QBBRNKNR" },
            { 485, "QRBBNKNR" },
            { 486, "QRBNKBNR" },
            { 487, "QRBNKNRB" },
            { 488, "QBRNBKNR" },
            { 489, "QRNBBKNR" },
            { 490, "QRNKBBNR" },
            { 491, "QRNKBNRB" },
            { 492, "QBRNKNBR" },
            { 493, "QRNBKNBR" },
            { 494, "QRNKNBBR" },
            { 495, "QRNKNRBB" },
            { 496, "BBRQNKNR" },
            { 497, "BRQBNKNR" },
            { 498, "BRQNKBNR" },
            { 499, "BRQNKNRB" },
            { 500, "RBBQNKNR" },
            { 501, "RQBBNKNR" },
            { 502, "RQBNKBNR" },
            { 503, "RQBNKNRB" },
            { 504, "RBQNBKNR" },
            { 505, "RQNBBKNR" },
            { 506, "RQNKBBNR" },
            { 507, "RQNKBNRB" },
            { 508, "RBQNKNBR" },
            { 509, "RQNBKNBR" },
            { 510, "RQNKNBBR" },
            { 511, "RQNKNRBB" },
            { 512, "BBRNQKNR" },
            { 513, "BRNBQKNR" },
            { 514, "BRNQKBNR" },
            { 515, "BRNQKNRB" },
            { 516, "RBBNQKNR" },
            { 517, "RNBBQKNR" },
            { 518, "RNBQKBNR" },
            { 519, "RNBQKNRB" },
            { 520, "RBNQBKNR" },
            { 521, "RNQBBKNR" },
            { 522, "RNQKBBNR" },
            { 523, "RNQKBNRB" },
            { 524, "RBNQKNBR" },
            { 525, "RNQBKNBR" },
            { 526, "RNQKNBBR" },
            { 527, "RNQKNRBB" },
            { 528, "BBRNKQNR" },
            { 529, "BRNBKQNR" },
            { 530, "BRNKQBNR" },
            { 531, "BRNKQNRB" },
            { 532, "RBBNKQNR" },
            { 533, "RNBBKQNR" },
            { 534, "RNBKQBNR" },
            { 535, "RNBKQNRB" },
            { 536, "RBNKBQNR" },
            { 537, "RNKBBQNR" },
            { 538, "RNKQBBNR" },
            { 539, "RNKQBNRB" },
            { 540, "RBNKQNBR" },
            { 541, "RNKBQNBR" },
            { 542, "RNKQNBBR" },
            { 543, "RNKQNRBB" },
            { 544, "BBRNKNQR" },
            { 545, "BRNBKNQR" },
            { 546, "BRNKNBQR" },
            { 547, "BRNKNQRB" },
            { 548, "RBBNKNQR" },
            { 549, "RNBBKNQR" },
            { 550, "RNBKNBQR" },
            { 551, "RNBKNQRB" },
            { 552, "RBNKBNQR" },
            { 553, "RNKBBNQR" },
            { 554, "RNKNBBQR" },
            { 555, "RNKNBQRB" },
            { 556, "RBNKNQBR" },
            { 557, "RNKBNQBR" },
            { 558, "RNKNQBBR" },
            { 559, "RNKNQRBB" },
            { 560, "BBRNKNRQ" },
            { 561, "BRNBKNRQ" },
            { 562, "BRNKNBRQ" },
            { 563, "BRNKNRQB" },
            { 564, "RBBNKNRQ" },
            { 565, "RNBBKNRQ" },
            { 566, "RNBKNBRQ" },
            { 567, "RNBKNRQB" },
            { 568, "RBNKBNRQ" },
            { 569, "RNKBBNRQ" },
            { 570, "RNKNBBRQ" },
            { 571, "RNKNBRQB" },
            { 572, "RBNKNRBQ" },
            { 573, "RNKBNRBQ" },
            { 574, "RNKNRBBQ" },
            { 575, "RNKNRQBB" },
            { 576, "BBQRNKRN" },
            { 577, "BQRBNKRN" },
            { 578, "BQRNKBRN" },
            { 579, "BQRNKRNB" },
            { 580, "QBBRNKRN" },
            { 581, "QRBBNKRN" },
            { 582, "QRBNKBRN" },
            { 583, "QRBNKRNB" },
            { 584, "QBRNBKRN" },
            { 585, "QRNBBKRN" },
            { 586, "QRNKBBRN" },
            { 587, "QRNKBRNB" },
            { 588, "QBRNKRBN" },
            { 589, "QRNBKRBN" },
            { 590, "QRNKRBBN" },
            { 591, "QRNKRNBB" },
            { 592, "BBRQNKRN" },
            { 593, "BRQBNKRN" },
            { 594, "BRQNKBRN" },
            { 595, "BRQNKRNB" },
            { 596, "RBBQNKRN" },
            { 597, "RQBBNKRN" },
            { 598, "RQBNKBRN" },
            { 599, "RQBNKRNB" },
            { 600, "RBQNBKRN" },
            { 601, "RQNBBKRN" },
            { 602, "RQNKBBRN" },
            { 603, "RQNKBRNB" },
            { 604, "RBQNKRBN" },
            { 605, "RQNBKRBN" },
            { 606, "RQNKRBBN" },
            { 607, "RQNKRNBB" },
            { 608, "BBRNQKRN" },
            { 609, "BRNBQKRN" },
            { 610, "BRNQKBRN" },
            { 611, "BRNQKRNB" },
            { 612, "RBBNQKRN" },
            { 613, "RNBBQKRN" },
            { 614, "RNBQKBRN" },
            { 615, "RNBQKRNB" },
            { 616, "RBNQBKRN" },
            { 617, "RNQBBKRN" },
            { 618, "RNQKBBRN" },
            { 619, "RNQKBRNB" },
            { 620, "RBNQKRBN" },
            { 621, "RNQBKRBN" },
            { 622, "RNQKRBBN" },
            { 623, "RNQKRNBB" },
            { 624, "BBRNKQRN" },
            { 625, "BRNBKQRN" },
            { 626, "BRNKQBRN" },
            { 627, "BRNKQRNB" },
            { 628, "RBBNKQRN" },
            { 629, "RNBBKQRN" },
            { 630, "RNBKQBRN" },
            { 631, "RNBKQRNB" },
            { 632, "RBNKBQRN" },
            { 633, "RNKBBQRN" },
            { 634, "RNKQBBRN" },
            { 635, "RNKQBRNB" },
            { 636, "RBNKQRBN" },
            { 637, "RNKBQRBN" },
            { 638, "RNKQRBBN" },
            { 639, "RNKQRNBB" },
            { 640, "BBRNKRQN" },
            { 641, "BRNBKRQN" },
            { 642, "BRNKRBQN" },
            { 643, "BRNKRQNB" },
            { 644, "RBBNKRQN" },
            { 645, "RNBBKRQN" },
            { 646, "RNBKRBQN" },
            { 647, "RNBKRQNB" },
            { 648, "RBNKBRQN" },
            { 649, "RNKBBRQN" },
            { 650, "RNKRBBQN" },
            { 651, "RNKRBQNB" },
            { 652, "RBNKRQBN" },
            { 653, "RNKBRQBN" },
            { 654, "RNKRQBBN" },
            { 655, "RNKRQNBB" },
            { 656, "BBRNKRNQ" },
            { 657, "BRNBKRNQ" },
            { 658, "BRNKRBNQ" },
            { 659, "BRNKRNQB" },
            { 660, "RBBNKRNQ" },
            { 661, "RNBBKRNQ" },
            { 662, "RNBKRBNQ" },
            { 663, "RNBKRNQB" },
            { 664, "RBNKBRNQ" },
            { 665, "RNKBBRNQ" },
            { 666, "RNKRBBNQ" },
            { 667, "RNKRBNQB" },
            { 668, "RBNKRNBQ" },
            { 669, "RNKBRNBQ" },
            { 670, "RNKRNBBQ" },
            { 671, "RNKRNQBB" },
            { 672, "BBQRKNNR" },
            { 673, "BQRBKNNR" },
            { 674, "BQRKNBNR" },
            { 675, "BQRKNNRB" },
            { 676, "QBBRKNNR" },
            { 677, "QRBBKNNR" },
            { 678, "QRBKNBNR" },
            { 679, "QRBKNNRB" },
            { 680, "QBRKBNNR" },
            { 681, "QRKBBNNR" },
            { 682, "QRKNBBNR" },
            { 683, "QRKNBNRB" },
            { 684, "QBRKNNBR" },
            { 685, "QRKBNNBR" },
            { 686, "QRKNNBBR" },
            { 687, "QRKNNRBB" },
            { 688, "BBRQKNNR" },
            { 689, "BRQBKNNR" },
            { 690, "BRQKNBNR" },
            { 691, "BRQKNNRB" },
            { 692, "RBBQKNNR" },
            { 693, "RQBBKNNR" },
            { 694, "RQBKNBNR" },
            { 695, "RQBKNNRB" },
            { 696, "RBQKBNNR" },
            { 697, "RQKBBNNR" },
            { 698, "RQKNBBNR" },
            { 699, "RQKNBNRB" },
            { 700, "RBQKNNBR" },
            { 701, "RQKBNNBR" },
            { 702, "RQKNNBBR" },
            { 703, "RQKNNRBB" },
            { 704, "BBRKQNNR" },
            { 705, "BRKBQNNR" },
            { 706, "BRKQNBNR" },
            { 707, "BRKQNNRB" },
            { 708, "RBBKQNNR" },
            { 709, "RKBBQNNR" },
            { 710, "RKBQNBNR" },
            { 711, "RKBQNNRB" },
            { 712, "RBKQBNNR" },
            { 713, "RKQBBNNR" },
            { 714, "RKQNBBNR" },
            { 715, "RKQNBNRB" },
            { 716, "RBKQNNBR" },
            { 717, "RKQBNNBR" },
            { 718, "RKQNNBBR" },
            { 719, "RKQNNRBB" },
            { 720, "BBRKNQNR" },
            { 721, "BRKBNQNR" },
            { 722, "BRKNQBNR" },
            { 723, "BRKNQNRB" },
            { 724, "RBBKNQNR" },
            { 725, "RKBBNQNR" },
            { 726, "RKBNQBNR" },
            { 727, "RKBNQNRB" },
            { 728, "RBKNBQNR" },
            { 729, "RKNBBQNR" },
            { 730, "RKNQBBNR" },
            { 731, "RKNQBNRB" },
            { 732, "RBKNQNBR" },
            { 733, "RKNBQNBR" },
            { 734, "RKNQNBBR" },
            { 735, "RKNQNRBB" },
            { 736, "BBRKNNQR" },
            { 737, "BRKBNNQR" },
            { 738, "BRKNNBQR" },
            { 739, "BRKNNQRB" },
            { 740, "RBBKNNQR" },
            { 741, "RKBBNNQR" },
            { 742, "RKBNNBQR" },
            { 743, "RKBNNQRB" },
            { 744, "RBKNBNQR" },
            { 745, "RKNBBNQR" },
            { 746, "RKNNBBQR" },
            { 747, "RKNNBQRB" },
            { 748, "RBKNNQBR" },
            { 749, "RKNBNQBR" },
            { 750, "RKNNQBBR" },
            { 751, "RKNNQRBB" },
            { 752, "BBRKNNRQ" },
            { 753, "BRKBNNRQ" },
            { 754, "BRKNNBRQ" },
            { 755, "BRKNNRQB" },
            { 756, "RBBKNNRQ" },
            { 757, "RKBBNNRQ" },
            { 758, "RKBNNBRQ" },
            { 759, "RKBNNRQB" },
            { 760, "RBKNBNRQ" },
            { 761, "RKNBBNRQ" },
            { 762, "RKNNBBRQ" },
            { 763, "RKNNBRQB" },
            { 764, "RBKNNRBQ" },
            { 765, "RKNBNRBQ" },
            { 766, "RKNNRBBQ" },
            { 767, "RKNNRQBB" },
            { 768, "BBQRKNRN" },
            { 769, "BQRBKNRN" },
            { 770, "BQRKNBRN" },
            { 771, "BQRKNRNB" },
            { 772, "QBBRKNRN" },
            { 773, "QRBBKNRN" },
            { 774, "QRBKNBRN" },
            { 775, "QRBKNRNB" },
            { 776, "QBRKBNRN" },
            { 777, "QRKBBNRN" },
            { 778, "QRKNBBRN" },
            { 779, "QRKNBRNB" },
            { 780, "QBRKNRBN" },
            { 781, "QRKBNRBN" },
            { 782, "QRKNRBBN" },
            { 783, "QRKNRNBB" },
            { 784, "BBRQKNRN" },
            { 785, "BRQBKNRN" },
            { 786, "BRQKNBRN" },
            { 787, "BRQKNRNB" },
            { 788, "RBBQKNRN" },
            { 789, "RQBBKNRN" },
            { 790, "RQBKNBRN" },
            { 791, "RQBKNRNB" },
            { 792, "RBQKBNRN" },
            { 793, "RQKBBNRN" },
            { 794, "RQKNBBRN" },
            { 795, "RQKNBRNB" },
            { 796, "RBQKNRBN" },
            { 797, "RQKBNRBN" },
            { 798, "RQKNRBBN" },
            { 799, "RQKNRNBB" },
            { 800, "BBRKQNRN" },
            { 801, "BRKBQNRN" },
            { 802, "BRKQNBRN" },
            { 803, "BRKQNRNB" },
            { 804, "RBBKQNRN" },
            { 805, "RKBBQNRN" },
            { 806, "RKBQNBRN" },
            { 807, "RKBQNRNB" },
            { 808, "RBKQBNRN" },
            { 809, "RKQBBNRN" },
            { 810, "RKQNBBRN" },
            { 811, "RKQNBRNB" },
            { 812, "RBKQNRBN" },
            { 813, "RKQBNRBN" },
            { 814, "RKQNRBBN" },
            { 815, "RKQNRNBB" },
            { 816, "BBRKNQRN" },
            { 817, "BRKBNQRN" },
            { 818, "BRKNQBRN" },
            { 819, "BRKNQRNB" },
            { 820, "RBBKNQRN" },
            { 821, "RKBBNQRN" },
            { 822, "RKBNQBRN" },
            { 823, "RKBNQRNB" },
            { 824, "RBKNBQRN" },
            { 825, "RKNBBQRN" },
            { 826, "RKNQBBRN" },
            { 827, "RKNQBRNB" },
            { 828, "RBKNQRBN" },
            { 829, "RKNBQRBN" },
            { 830, "RKNQRBBN" },
            { 831, "RKNQRNBB" },
            { 832, "BBRKNRQN" },
            { 833, "BRKBNRQN" },
            { 834, "BRKNRBQN" },
            { 835, "BRKNRQNB" },
            { 836, "RBBKNRQN" },
            { 837, "RKBBNRQN" },
            { 838, "RKBNRBQN" },
            { 839, "RKBNRQNB" },
            { 840, "RBKNBRQN" },
            { 841, "RKNBBRQN" },
            { 842, "RKNRBBQN" },
            { 843, "RKNRBQNB" },
            { 844, "RBKNRQBN" },
            { 845, "RKNBRQBN" },
            { 846, "RKNRQBBN" },
            { 847, "RKNRQNBB" },
            { 848, "BBRKNRNQ" },
            { 849, "BRKBNRNQ" },
            { 850, "BRKNRBNQ" },
            { 851, "BRKNRNQB" },
            { 852, "RBBKNRNQ" },
            { 853, "RKBBNRNQ" },
            { 854, "RKBNRBNQ" },
            { 855, "RKBNRNQB" },
            { 856, "RBKNBRNQ" },
            { 857, "RKNBBRNQ" },
            { 858, "RKNRBBNQ" },
            { 859, "RKNRBNQB" },
            { 860, "RBKNRNBQ" },
            { 861, "RKNBRNBQ" },
            { 862, "RKNRNBBQ" },
            { 863, "RKNRNQBB" },
            { 864, "BBQRKRNN" },
            { 865, "BQRBKRNN" },
            { 866, "BQRKRBNN" },
            { 867, "BQRKRNNB" },
            { 868, "QBBRKRNN" },
            { 869, "QRBBKRNN" },
            { 870, "QRBKRBNN" },
            { 871, "QRBKRNNB" },
            { 872, "QBRKBRNN" },
            { 873, "QRKBBRNN" },
            { 874, "QRKRBBNN" },
            { 875, "QRKRBNNB" },
            { 876, "QBRKRNBN" },
            { 877, "QRKBRNBN" },
            { 878, "QRKRNBBN" },
            { 879, "QRKRNNBB" },
            { 880, "BBRQKRNN" },
            { 881, "BRQBKRNN" },
            { 882, "BRQKRBNN" },
            { 883, "BRQKRNNB" },
            { 884, "RBBQKRNN" },
            { 885, "RQBBKRNN" },
            { 886, "RQBKRBNN" },
            { 887, "RQBKRNNB" },
            { 888, "RBQKBRNN" },
            { 889, "RQKBBRNN" },
            { 890, "RQKRBBNN" },
            { 891, "RQKRBNNB" },
            { 892, "RBQKRNBN" },
            { 893, "RQKBRNBN" },
            { 894, "RQKRNBBN" },
            { 895, "RQKRNNBB" },
            { 896, "BBRKQRNN" },
            { 897, "BRKBQRNN" },
            { 898, "BRKQRBNN" },
            { 899, "BRKQRNNB" },
            { 900, "RBBKQRNN" },
            { 901, "RKBBQRNN" },
            { 902, "RKBQRBNN" },
            { 903, "RKBQRNNB" },
            { 904, "RBKQBRNN" },
            { 905, "RKQBBRNN" },
            { 906, "RKQRBBNN" },
            { 907, "RKQRBNNB" },
            { 908, "RBKQRNBN" },
            { 909, "RKQBRNBN" },
            { 910, "RKQRNBBN" },
            { 911, "RKQRNNBB" },
            { 912, "BBRKRQNN" },
            { 913, "BRKBRQNN" },
            { 914, "BRKRQBNN" },
            { 915, "BRKRQNNB" },
            { 916, "RBBKRQNN" },
            { 917, "RKBBRQNN" },
            { 918, "RKBRQBNN" },
            { 919, "RKBRQNNB" },
            { 920, "RBKRBQNN" },
            { 921, "RKRBBQNN" },
            { 922, "RKRQBBNN" },
            { 923, "RKRQBNNB" },
            { 924, "RBKRQNBN" },
            { 925, "RKRBQNBN" },
            { 926, "RKRQNBBN" },
            { 927, "RKRQNNBB" },
            { 928, "BBRKRNQN" },
            { 929, "BRKBRNQN" },
            { 930, "BRKRNBQN" },
            { 931, "BRKRNQNB" },
            { 932, "RBBKRNQN" },
            { 933, "RKBBRNQN" },
            { 934, "RKBRNBQN" },
            { 935, "RKBRNQNB" },
            { 936, "RBKRBNQN" },
            { 937, "RKRBBNQN" },
            { 938, "RKRNBBQN" },
            { 939, "RKRNBQNB" },
            { 940, "RBKRNQBN" },
            { 941, "RKRBNQBN" },
            { 942, "RKRNQBBN" },
            { 943, "RKRNQNBB" },
            { 944, "BBRKRNNQ" },
            { 945, "BRKBRNNQ" },
            { 946, "BRKRNBNQ" },
            { 947, "BRKRNNQB" },
            { 948, "RBBKRNNQ" },
            { 949, "RKBBRNNQ" },
            { 950, "RKBRNBNQ" },
            { 951, "RKBRNNQB" },
            { 952, "RBKRBNNQ" },
            { 953, "RKRBBNNQ" },
            { 954, "RKRNBBNQ" },
            { 955, "RKRNBNQB" },
            { 956, "RBKRNNBQ" },
            { 957, "RKRBNNBQ" },
            { 958, "RKRNNBBQ" },
            { 959, "RKRNNQBB" }
        };

        // format: { number, "row 1" + "row 2" }
        static Dictionary<int, string> racingKingsStartArrays = new Dictionary<int, string>()
        {
            { 0, "BBQKRRNN"},
            { 1, "BBQNRRNK"},
            { 2, "BBQNRRKN"},
            { 3, "BBKQRRNN"},
            { 4, "BQNKRRBN"},
            { 5, "QBBNRRNK"},
            { 6, "BQNBRRKN"},
            { 7, "QBKNRRNB"},
            { 8, "BQNKBRRN"},
            { 9, "QBNNRBRK"},
            { 10, "BQNNBRKR"},
            { 11, "QBKNRBRN"},
            { 12, "QBBKRRNN"},
            { 13, "BQNBRRNK"},
            { 14, "QBBNRRKN"},
            { 15, "BQKBRRNN"},
            { 16, "QNBKRRBN"},
            { 17, "QNBBRRNK"},
            { 18, "QNBBRRKN"},
            { 19, "QNKBRRNB"},
            { 20, "QNBKBRRN"},
            { 21, "QNNBRBRK"},
            { 22, "QNBNBRKR"},
            { 23, "QNKBRBRN"},
            { 24, "QBNKRRNB"},
            { 25, "BQNNRRBK"},
            { 26, "QBNNRRKB"},
            { 27, "BQKNRRBN"},
            { 28, "QNNKRRBB"},
            { 29, "QNBNRRBK"},
            { 30, "QNNBRRKB"},
            { 31, "QNKNRRBB"},
            { 32, "QNNKBRRB"},
            { 33, "QNNRRBBK"},
            { 34, "QNNRBRKB"},
            { 35, "QNKNRBBR"},
            { 36, "QBNKRBRN"},
            { 37, "BQNNBRRK"},
            { 38, "QBNNRBKR"},
            { 39, "BQKNBRRN"},
            { 40, "QNNKRBBR"},
            { 41, "QNBNBRRK"},
            { 42, "QNNBRBKR"},
            { 43, "QNKNBRRB"},
            { 44, "QNNKBBRR"},
            { 45, "QNNRBBRK"},
            { 46, "QNNRBBKR"},
            { 47, "QNKNBBRR"},
            { 48, "BBNKRRNQ"},
            { 49, "BBNQRRNK"},
            { 50, "BBNQRRKN"},
            { 51, "BBKNRRNQ"},
            { 52, "BNQKRRBN"},
            { 53, "NBBQRRNK"},
            { 54, "BNQBRRKN"},
            { 55, "NBKQRRNB"},
            { 56, "BNQKBRRN"},
            { 57, "NBQNRBRK"},
            { 58, "BNQNBRKR"},
            { 59, "NBKQRBRN"},
            { 60, "NBBKRRNQ"},
            { 61, "BNQBRRNK"},
            { 62, "NBBQRRKN"},
            { 63, "BNKBRRNQ"},
            { 64, "NQBKRRBN"},
            { 65, "NQBBRRNK"},
            { 66, "NQBBRRKN"},
            { 67, "NQKBRRNB"},
            { 68, "NQBKBRRN"},
            { 69, "NQNBRBRK"},
            { 70, "NQBNBRKR"},
            { 71, "NQKBRBRN"},
            { 72, "NBQKRRNB"},
            { 73, "BNQNRRBK"},
            { 74, "NBQNRRKB"},
            { 75, "BNKQRRBN"},
            { 76, "NQNKRRBB"},
            { 77, "NQBNRRBK"},
            { 78, "NQNBRRKB"},
            { 79, "NQKNRRBB"},
            { 80, "NQNKBRRB"},
            { 81, "NQNRRBBK"},
            { 82, "NQNRBRKB"},
            { 83, "NQKNRBBR"},
            { 84, "NBQKRBRN"},
            { 85, "BNQNBRRK"},
            { 86, "NBQNRBKR"},
            { 87, "BNKQBRRN"},
            { 88, "NQNKRBBR"},
            { 89, "NQBNBRRK"},
            { 90, "NQNBRBKR"},
            { 91, "NQKNBRRB"},
            { 92, "NQNKBBRR"},
            { 93, "NQNRBBRK"},
            { 94, "NQNRBBKR"},
            { 95, "NQKNBBRR"},
            { 96, "BBNKRRQN"},
            { 97, "BBNNRRQK"},
            { 98, "BBNNRRKQ"},
            { 99, "BBKNRRQN"},
            { 100, "BNNKRRBQ"},
            { 101, "NBBNRRQK"},
            { 102, "BNNBRRKQ"},
            { 103, "NBKNRRQB"},
            { 104, "BNNKBRRQ"},
            { 105, "NBNQRBRK"},
            { 106, "BNNQBRKR"},
            { 107, "NBKNRBRQ"},
            { 108, "NBBKRRQN"},
            { 109, "BNNBRRQK"},
            { 110, "NBBNRRKQ"},
            { 111, "BNKBRRQN"},
            { 112, "NNBKRRBQ"},
            { 113, "NNBBRRQK"},
            { 114, "NNBBRRKQ"},
            { 115, "NNKBRRQB"},
            { 116, "NNBKBRRQ"},
            { 117, "NNQBRBRK"},
            { 118, "NNBQBRKR"},
            { 119, "NNKBRBRQ"},
            { 120, "NBNKRRQB"},
            { 121, "BNNQRRBK"},
            { 122, "NBNQRRKB"},
            { 123, "BNKNRRBQ"},
            { 124, "NNQKRRBB"},
            { 125, "NNBQRRBK"},
            { 126, "NNQBRRKB"},
            { 127, "NNKQRRBB"},
            { 128, "NNQKBRRB"},
            { 129, "NNQRRBBK"},
            { 130, "NNQRBRKB"},
            { 131, "NNKQRBBR"},
            { 132, "NBNKRBRQ"},
            { 133, "BNNQBRRK"},
            { 134, "NBNQRBKR"},
            { 135, "BNKNBRRQ"},
            { 136, "NNQKRBBR"},
            { 137, "NNBQBRRK"},
            { 138, "NNQBRBKR"},
            { 139, "NNKQBRRB"},
            { 140, "NNQKBBRR"},
            { 141, "NNQRBBRK"},
            { 142, "NNQRBBKR"},
            { 143, "NNKQBBRR"},
            { 144, "BBNKRQRN"},
            { 145, "BBNNRQRK"},
            { 146, "BBNNRQKR"},
            { 147, "BBKNRQRN"},
            { 148, "BNNKRQBR"},
            { 149, "NBBNRQRK"},
            { 150, "BNNBRQKR"},
            { 151, "NBKNRQRB"},
            { 152, "BNNKBRQR"},
            { 153, "NBNRRBQK"},
            { 154, "BNNRBRKQ"},
            { 155, "NBKNRBQR"},
            { 156, "NBBKRQRN"},
            { 157, "BNNBRQRK"},
            { 158, "NBBNRQKR"},
            { 159, "BNKBRQRN"},
            { 160, "NNBKRQBR"},
            { 161, "NNBBRQRK"},
            { 162, "NNBBRQKR"},
            { 163, "NNKBRQRB"},
            { 164, "NNBKBRQR"},
            { 165, "NNRBRBQK"},
            { 166, "NNBRBRKQ"},
            { 167, "NNKBRBQR"},
            { 168, "NBNKRQRB"},
            { 169, "BNNRRQBK"},
            { 170, "NBNRRQKB"},
            { 171, "BNKNRQBR"},
            { 172, "NNRKRQBB"},
            { 173, "NNBRRQBK"},
            { 174, "NNRBRQKB"},
            { 175, "NNKRRQBB"},
            { 176, "NNRKBRQB"},
            { 177, "NNRQRBBK"},
            { 178, "NNRQBRKB"},
            { 179, "NNKRRBBQ"},
            { 180, "NBNKRBQR"},
            { 181, "BNNRBRQK"},
            { 182, "NBNRRBKQ"},
            { 183, "BNKNBRQR"},
            { 184, "NNRKRBBQ"},
            { 185, "NNBRBRQK"},
            { 186, "NNRBRBKQ"},
            { 187, "NNKRBRQB"},
            { 188, "NNRKBBRQ"},
            { 189, "NNRQBBRK"},
            { 190, "NNRQBBKR"},
            { 191, "NNKRBBRQ"},
            { 192, "BBNKQRRN"},
            { 193, "BBNNQRRK"},
            { 194, "BBNNQRKR"},
            { 195, "BBKNQRRN"},
            { 196, "BNNKQRBR"},
            { 197, "NBBNQRRK"},
            { 198, "BNNBQRKR"},
            { 199, "NBKNQRRB"},
            { 200, "BNNKBQRR"},
            { 201, "NBNRQBRK"},
            { 202, "BNNRBQKR"},
            { 203, "NBKNQBRR"},
            { 204, "NBBKQRRN"},
            { 205, "BNNBQRRK"},
            { 206, "NBBNQRKR"},
            { 207, "BNKBQRRN"},
            { 208, "NNBKQRBR"},
            { 209, "NNBBQRRK"},
            { 210, "NNBBQRKR"},
            { 211, "NNKBQRRB"},
            { 212, "NNBKBQRR"},
            { 213, "NNRBQBRK"},
            { 214, "NNBRBQKR"},
            { 215, "NNKBQBRR"},
            { 216, "NBNKQRRB"},
            { 217, "BNNRQRBK"},
            { 218, "NBNRQRKB"},
            { 219, "BNKNQRBR"},
            { 220, "NNRKQRBB"},
            { 221, "NNBRQRBK"},
            { 222, "NNRBQRKB"},
            { 223, "NNKRQRBB"},
            { 224, "NNRKBQRB"},
            { 225, "NNRRQBBK"},
            { 226, "NNRRBQKB"},
            { 227, "NNKRQBBR"},
            { 228, "NBNKQBRR"},
            { 229, "BNNRBQRK"},
            { 230, "NBNRQBKR"},
            { 231, "BNKNBQRR"},
            { 232, "NNRKQBBR"},
            { 233, "NNBRBQRK"},
            { 234, "NNRBQBKR"},
            { 235, "NNKRBQRB"},
            { 236, "NNRKBBQR"},
            { 237, "NNRRBBQK"},
            { 238, "NNRRBBKQ"},
            { 239, "NNKRBBQR"},
            { 240, "BBQKRNRN"},
            { 241, "BBQNRNRK"},
            { 242, "BBQNRNKR"},
            { 243, "BBKQRNRN"},
            { 244, "BQNKRNBR"},
            { 245, "QBBNRNRK"},
            { 246, "BQNBRNKR"},
            { 247, "QBKNRNRB"},
            { 248, "BQNKBRNR"},
            { 249, "QBNRRBNK"},
            { 250, "BQNRBRKN"},
            { 251, "QBKNRBNR"},
            { 252, "QBBKRNRN"},
            { 253, "BQNBRNRK"},
            { 254, "QBBNRNKR"},
            { 255, "BQKBRNRN"},
            { 256, "QNBKRNBR"},
            { 257, "QNBBRNRK"},
            { 258, "QNBBRNKR"},
            { 259, "QNKBRNRB"},
            { 260, "QNBKBRNR"},
            { 261, "QNRBRBNK"},
            { 262, "QNBRBRKN"},
            { 263, "QNKBRBNR"},
            { 264, "QBNKRNRB"},
            { 265, "BQNRRNBK"},
            { 266, "QBNRRNKB"},
            { 267, "BQKNRNBR"},
            { 268, "QNRKRNBB"},
            { 269, "QNBRRNBK"},
            { 270, "QNRBRNKB"},
            { 271, "QNKRRNBB"},
            { 272, "QNRKBRNB"},
            { 273, "QNRNRBBK"},
            { 274, "QNRNBRKB"},
            { 275, "QNKRRBBN"},
            { 276, "QBNKRBNR"},
            { 277, "BQNRBRNK"},
            { 278, "QBNRRBKN"},
            { 279, "BQKNBRNR"},
            { 280, "QNRKRBBN"},
            { 281, "QNBRBRNK"},
            { 282, "QNRBRBKN"},
            { 283, "QNKRBRNB"},
            { 284, "QNRKBBRN"},
            { 285, "QNRNBBRK"},
            { 286, "QNRNBBKR"},
            { 287, "QNKRBBRN"},
            { 288, "BBNKRNRQ"},
            { 289, "BBNQRNRK"},
            { 290, "BBNQRNKR"},
            { 291, "BBKNRNRQ"},
            { 292, "BNQKRNBR"},
            { 293, "NBBQRNRK"},
            { 294, "BNQBRNKR"},
            { 295, "NBKQRNRB"},
            { 296, "BNQKBRNR"},
            { 297, "NBQRRBNK"},
            { 298, "BNQRBRKN"},
            { 299, "NBKQRBNR"},
            { 300, "NBBKRNRQ"},
            { 301, "BNQBRNRK"},
            { 302, "NBBQRNKR"},
            { 303, "BNKBRNRQ"},
            { 304, "NQBKRNBR"},
            { 305, "NQBBRNRK"},
            { 306, "NQBBRNKR"},
            { 307, "NQKBRNRB"},
            { 308, "NQBKBRNR"},
            { 309, "NQRBRBNK"},
            { 310, "NQBRBRKN"},
            { 311, "NQKBRBNR"},
            { 312, "NBQKRNRB"},
            { 313, "BNQRRNBK"},
            { 314, "NBQRRNKB"},
            { 315, "BNKQRNBR"},
            { 316, "NQRKRNBB"},
            { 317, "NQBRRNBK"},
            { 318, "NQRBRNKB"},
            { 319, "NQKRRNBB"},
            { 320, "NQRKBRNB"},
            { 321, "NQRNRBBK"},
            { 322, "NQRNBRKB"},
            { 323, "NQKRRBBN"},
            { 324, "NBQKRBNR"},
            { 325, "BNQRBRNK"},
            { 326, "NBQRRBKN"},
            { 327, "BNKQBRNR"},
            { 328, "NQRKRBBN"},
            { 329, "NQBRBRNK"},
            { 330, "NQRBRBKN"},
            { 331, "NQKRBRNB"},
            { 332, "NQRKBBRN"},
            { 333, "NQRNBBRK"},
            { 334, "NQRNBBKR"},
            { 335, "NQKRBBRN"},
            { 336, "BBNKRNQR"},
            { 337, "BBNRRNQK"},
            { 338, "BBNRRNKQ"},
            { 339, "BBKNRNQR"},
            { 340, "BNRKRNBQ"},
            { 341, "NBBRRNQK"},
            { 342, "BNRBRNKQ"},
            { 343, "NBKRRNQB"},
            { 344, "BNRKBRNQ"},
            { 345, "NBRQRBNK"},
            { 346, "BNRQBRKN"},
            { 347, "NBKRRBNQ"},
            { 348, "NBBKRNQR"},
            { 349, "BNRBRNQK"},
            { 350, "NBBRRNKQ"},
            { 351, "BNKBRNQR"},
            { 352, "NRBKRNBQ"},
            { 353, "NRBBRNQK"},
            { 354, "NRBBRNKQ"},
            { 355, "NRKBRNQB"},
            { 356, "NRBKBRNQ"},
            { 357, "NRQBRBNK"},
            { 358, "NRBQBRKN"},
            { 359, "NRKBRBNQ"},
            { 360, "NBRKRNQB"},
            { 361, "BNRQRNBK"},
            { 362, "NBRQRNKB"},
            { 363, "BNKRRNBQ"},
            { 364, "NRQKRNBB"},
            { 365, "NRBQRNBK"},
            { 366, "NRQBRNKB"},
            { 367, "NRKQRNBB"},
            { 368, "NRQKBRNB"},
            { 369, "NRQNRBBK"},
            { 370, "NRQNBRKB"},
            { 371, "NRKQRBBN"},
            { 372, "NBRKRBNQ"},
            { 373, "BNRQBRNK"},
            { 374, "NBRQRBKN"},
            { 375, "BNKRBRNQ"},
            { 376, "NRQKRBBN"},
            { 377, "NRBQBRNK"},
            { 378, "NRQBRBKN"},
            { 379, "NRKQBRNB"},
            { 380, "NRQKBBRN"},
            { 381, "NRQNBBRK"},
            { 382, "NRQNBBKR"},
            { 383, "NRKQBBRN"},
            { 384, "BBNKRQNR"},
            { 385, "BBNRRQNK"},
            { 386, "BBNRRQKN"},
            { 387, "BBKNRQNR"},
            { 388, "BNRKRQBN"},
            { 389, "NBBRRQNK"},
            { 390, "BNRBRQKN"},
            { 391, "NBKRRQNB"},
            { 392, "BNRKBRQN"},
            { 393, "NBRNRBQK"},
            { 394, "BNRNBRKQ"},
            { 395, "NBKRRBQN"},
            { 396, "NBBKRQNR"},
            { 397, "BNRBRQNK"},
            { 398, "NBBRRQKN"},
            { 399, "BNKBRQNR"},
            { 400, "NRBKRQBN"},
            { 401, "NRBBRQNK"},
            { 402, "NRBBRQKN"},
            { 403, "NRKBRQNB"},
            { 404, "NRBKBRQN"},
            { 405, "NRNBRBQK"},
            { 406, "NRBNBRKQ"},
            { 407, "NRKBRBQN"},
            { 408, "NBRKRQNB"},
            { 409, "BNRNRQBK"},
            { 410, "NBRNRQKB"},
            { 411, "BNKRRQBN"},
            { 412, "NRNKRQBB"},
            { 413, "NRBNRQBK"},
            { 414, "NRNBRQKB"},
            { 415, "NRKNRQBB"},
            { 416, "NRNKBRQB"},
            { 417, "NRNQRBBK"},
            { 418, "NRNQBRKB"},
            { 419, "NRKNRBBQ"},
            { 420, "NBRKRBQN"},
            { 421, "BNRNBRQK"},
            { 422, "NBRNRBKQ"},
            { 423, "BNKRBRQN"},
            { 424, "NRNKRBBQ"},
            { 425, "NRBNBRQK"},
            { 426, "NRNBRBKQ"},
            { 427, "NRKNBRQB"},
            { 428, "NRNKBBRQ"},
            { 429, "NRNQBBRK"},
            { 430, "NRNQBBKR"},
            { 431, "NRKNBBRQ"},
            { 432, "BBNKQRNR"},
            { 433, "BBNRQRNK"},
            { 434, "BBNRQRKN"},
            { 435, "BBKNQRNR"},
            { 436, "BNRKQRBN"},
            { 437, "NBBRQRNK"},
            { 438, "BNRBQRKN"},
            { 439, "NBKRQRNB"},
            { 440, "BNRKBQRN"},
            { 441, "NBRNQBRK"},
            { 442, "BNRNBQKR"},
            { 443, "NBKRQBRN"},
            { 444, "NBBKQRNR"},
            { 445, "BNRBQRNK"},
            { 446, "NBBRQRKN"},
            { 447, "BNKBQRNR"},
            { 448, "NRBKQRBN"},
            { 449, "NRBBQRNK"},
            { 450, "NRBBQRKN"},
            { 451, "NRKBQRNB"},
            { 452, "NRBKBQRN"},
            { 453, "NRNBQBRK"},
            { 454, "NRBNBQKR"},
            { 455, "NRKBQBRN"},
            { 456, "NBRKQRNB"},
            { 457, "BNRNQRBK"},
            { 458, "NBRNQRKB"},
            { 459, "BNKRQRBN"},
            { 460, "NRNKQRBB"},
            { 461, "NRBNQRBK"},
            { 462, "NRNBQRKB"},
            { 463, "NRKNQRBB"},
            { 464, "NRNKBQRB"},
            { 465, "NRNRQBBK"},
            { 466, "NRNRBQKB"},
            { 467, "NRKNQBBR"},
            { 468, "NBRKQBRN"},
            { 469, "BNRNBQRK"},
            { 470, "NBRNQBKR"},
            { 471, "BNKRBQRN"},
            { 472, "NRNKQBBR"},
            { 473, "NRBNBQRK"},
            { 474, "NRNBQBKR"},
            { 475, "NRKNBQRB"},
            { 476, "NRNKBBQR"},
            { 477, "NRNRBBQK"},
            { 478, "NRNRBBKQ"},
            { 479, "NRKNBBQR"},
            { 480, "BBQKNRRN"},
            { 481, "BBQNNRRK"},
            { 482, "BBQNNRKR"},
            { 483, "BBKQNRRN"},
            { 484, "BQNKNRBR"},
            { 485, "QBBNNRRK"},
            { 486, "BQNBNRKR"},
            { 487, "QBKNNRRB"},
            { 488, "BQNKBNRR"},
            { 489, "QBNRNBRK"},
            { 490, "BQNRBNKR"},
            { 491, "QBKNNBRR"},
            { 492, "QBBKNRRN"},
            { 493, "BQNBNRRK"},
            { 494, "QBBNNRKR"},
            { 495, "BQKBNRRN"},
            { 496, "QNBKNRBR"},
            { 497, "QNBBNRRK"},
            { 498, "QNBBNRKR"},
            { 499, "QNKBNRRB"},
            { 500, "QNBKBNRR"},
            { 501, "QNRBNBRK"},
            { 502, "QNBRBNKR"},
            { 503, "QNKBNBRR"},
            { 504, "QBNKNRRB"},
            { 505, "BQNRNRBK"},
            { 506, "QBNRNRKB"},
            { 507, "BQKNNRBR"},
            { 508, "QNRKNRBB"},
            { 509, "QNBRNRBK"},
            { 510, "QNRBNRKB"},
            { 511, "QNKRNRBB"},
            { 512, "QNRKBNRB"},
            { 513, "QNRRNBBK"},
            { 514, "QNRRBNKB"},
            { 515, "QNKRNBBR"},
            { 516, "QBNKNBRR"},
            { 517, "BQNRBNRK"},
            { 518, "QBNRNBKR"},
            { 519, "BQKNBNRR"},
            { 520, "QNRKNBBR"},
            { 521, "QNBRBNRK"},
            { 522, "QNRBNBKR"},
            { 523, "QNKRBNRB"},
            { 524, "QNRKBBNR"},
            { 525, "QNRRBBNK"},
            { 526, "QNRRBBKN"},
            { 527, "QNKRBBNR"},
            { 528, "BBNKNRRQ"},
            { 529, "BBNQNRRK"},
            { 530, "BBNQNRKR"},
            { 531, "BBKNNRRQ"},
            { 532, "BNQKNRBR"},
            { 533, "NBBQNRRK"},
            { 534, "BNQBNRKR"},
            { 535, "NBKQNRRB"},
            { 536, "BNQKBNRR"},
            { 537, "NBQRNBRK"},
            { 538, "BNQRBNKR"},
            { 539, "NBKQNBRR"},
            { 540, "NBBKNRRQ"},
            { 541, "BNQBNRRK"},
            { 542, "NBBQNRKR"},
            { 543, "BNKBNRRQ"},
            { 544, "NQBKNRBR"},
            { 545, "NQBBNRRK"},
            { 546, "NQBBNRKR"},
            { 547, "NQKBNRRB"},
            { 548, "NQBKBNRR"},
            { 549, "NQRBNBRK"},
            { 550, "NQBRBNKR"},
            { 551, "NQKBNBRR"},
            { 552, "NBQKNRRB"},
            { 553, "BNQRNRBK"},
            { 554, "NBQRNRKB"},
            { 555, "BNKQNRBR"},
            { 556, "NQRKNRBB"},
            { 557, "NQBRNRBK"},
            { 558, "NQRBNRKB"},
            { 559, "NQKRNRBB"},
            { 560, "NQRKBNRB"},
            { 561, "NQRRNBBK"},
            { 562, "NQRRBNKB"},
            { 563, "NQKRNBBR"},
            { 564, "NBQKNBRR"},
            { 565, "BNQRBNRK"},
            { 566, "NBQRNBKR"},
            { 567, "BNKQBNRR"},
            { 568, "NQRKNBBR"},
            { 569, "NQBRBNRK"},
            { 570, "NQRBNBKR"},
            { 571, "NQKRBNRB"},
            { 572, "NQRKBBNR"},
            { 573, "NQRRBBNK"},
            { 574, "NQRRBBKN"},
            { 575, "NQKRBBNR"},
            { 576, "BBNKNRQR"},
            { 577, "BBNRNRQK"},
            { 578, "BBNRNRKQ"},
            { 579, "BBKNNRQR"},
            { 580, "BNRKNRBQ"},
            { 581, "NBBRNRQK"},
            { 582, "BNRBNRKQ"},
            { 583, "NBKRNRQB"},
            { 584, "BNRKBNRQ"},
            { 585, "NBRQNBRK"},
            { 586, "BNRQBNKR"},
            { 587, "NBKRNBRQ"},
            { 588, "NBBKNRQR"},
            { 589, "BNRBNRQK"},
            { 590, "NBBRNRKQ"},
            { 591, "BNKBNRQR"},
            { 592, "NRBKNRBQ"},
            { 593, "NRBBNRQK"},
            { 594, "NRBBNRKQ"},
            { 595, "NRKBNRQB"},
            { 596, "NRBKBNRQ"},
            { 597, "NRQBNBRK"},
            { 598, "NRBQBNKR"},
            { 599, "NRKBNBRQ"},
            { 600, "NBRKNRQB"},
            { 601, "BNRQNRBK"},
            { 602, "NBRQNRKB"},
            { 603, "BNKRNRBQ"},
            { 604, "NRQKNRBB"},
            { 605, "NRBQNRBK"},
            { 606, "NRQBNRKB"},
            { 607, "NRKQNRBB"},
            { 608, "NRQKBNRB"},
            { 609, "NRQRNBBK"},
            { 610, "NRQRBNKB"},
            { 611, "NRKQNBBR"},
            { 612, "NBRKNBRQ"},
            { 613, "BNRQBNRK"},
            { 614, "NBRQNBKR"},
            { 615, "BNKRBNRQ"},
            { 616, "NRQKNBBR"},
            { 617, "NRBQBNRK"},
            { 618, "NRQBNBKR"},
            { 619, "NRKQBNRB"},
            { 620, "NRQKBBNR"},
            { 621, "NRQRBBNK"},
            { 622, "NRQRBBKN"},
            { 623, "NRKQBBNR"},
            { 624, "BBNKNQRR"},
            { 625, "BBNRNQRK"},
            { 626, "BBNRNQKR"},
            { 627, "BBKNNQRR"},
            { 628, "BNRKNQBR"},
            { 629, "NBBRNQRK"},
            { 630, "BNRBNQKR"},
            { 631, "NBKRNQRB"},
            { 632, "BNRKBNQR"},
            { 633, "NBRRNBQK"},
            { 634, "BNRRBNKQ"},
            { 635, "NBKRNBQR"},
            { 636, "NBBKNQRR"},
            { 637, "BNRBNQRK"},
            { 638, "NBBRNQKR"},
            { 639, "BNKBNQRR"},
            { 640, "NRBKNQBR"},
            { 641, "NRBBNQRK"},
            { 642, "NRBBNQKR"},
            { 643, "NRKBNQRB"},
            { 644, "NRBKBNQR"},
            { 645, "NRRBNBQK"},
            { 646, "NRBRBNKQ"},
            { 647, "NRKBNBQR"},
            { 648, "NBRKNQRB"},
            { 649, "BNRRNQBK"},
            { 650, "NBRRNQKB"},
            { 651, "BNKRNQBR"},
            { 652, "NRRKNQBB"},
            { 653, "NRBRNQBK"},
            { 654, "NRRBNQKB"},
            { 655, "NRKRNQBB"},
            { 656, "NRRKBNQB"},
            { 657, "NRRQNBBK"},
            { 658, "NRRQBNKB"},
            { 659, "NRKRNBBQ"},
            { 660, "NBRKNBQR"},
            { 661, "BNRRBNQK"},
            { 662, "NBRRNBKQ"},
            { 663, "BNKRBNQR"},
            { 664, "NRRKNBBQ"},
            { 665, "NRBRBNQK"},
            { 666, "NRRBNBKQ"},
            { 667, "NRKRBNQB"},
            { 668, "NRRKBBNQ"},
            { 669, "NRRQBBNK"},
            { 670, "NRRQBBKN"},
            { 671, "NRKRBBNQ"},
            { 672, "BBNKQNRR"},
            { 673, "BBNRQNRK"},
            { 674, "BBNRQNKR"},
            { 675, "BBKNQNRR"},
            { 676, "BNRKQNBR"},
            { 677, "NBBRQNRK"},
            { 678, "BNRBQNKR"},
            { 679, "NBKRQNRB"},
            { 680, "BNRKBQNR"},
            { 681, "NBRRQBNK"},
            { 682, "BNRRBQKN"},
            { 683, "NBKRQBNR"},
            { 684, "NBBKQNRR"},
            { 685, "BNRBQNRK"},
            { 686, "NBBRQNKR"},
            { 687, "BNKBQNRR"},
            { 688, "NRBKQNBR"},
            { 689, "NRBBQNRK"},
            { 690, "NRBBQNKR"},
            { 691, "NRKBQNRB"},
            { 692, "NRBKBQNR"},
            { 693, "NRRBQBNK"},
            { 694, "NRBRBQKN"},
            { 695, "NRKBQBNR"},
            { 696, "NBRKQNRB"},
            { 697, "BNRRQNBK"},
            { 698, "NBRRQNKB"},
            { 699, "BNKRQNBR"},
            { 700, "NRRKQNBB"},
            { 701, "NRBRQNBK"},
            { 702, "NRRBQNKB"},
            { 703, "NRKRQNBB"},
            { 704, "NRRKBQNB"},
            { 705, "NRRNQBBK"},
            { 706, "NRRNBQKB"},
            { 707, "NRKRQBBN"},
            { 708, "NBRKQBNR"},
            { 709, "BNRRBQNK"},
            { 710, "NBRRQBKN"},
            { 711, "BNKRBQNR"},
            { 712, "NRRKQBBN"},
            { 713, "NRBRBQNK"},
            { 714, "NRRBQBKN"},
            { 715, "NRKRBQNB"},
            { 716, "NRRKBBQN"},
            { 717, "NRRNBBQK"},
            { 718, "NRRNBBKQ"},
            { 719, "NRKRBBQN"},
            { 720, "BBQKRNNR"},
            { 721, "BBQRRNNK"},
            { 722, "BBQRRNKN"},
            { 723, "BBKQRNNR"},
            { 724, "BQRKRNBN"},
            { 725, "QBBRRNNK"},
            { 726, "BQRBRNKN"},
            { 727, "QBKRRNNB"},
            { 728, "BQRKBRNN"},
            { 729, "QBRNRBNK"},
            { 730, "BQRNBRKN"},
            { 731, "QBKRRBNN"},
            { 732, "QBBKRNNR"},
            { 733, "BQRBRNNK"},
            { 734, "QBBRRNKN"},
            { 735, "BQKBRNNR"},
            { 736, "QRBKRNBN"},
            { 737, "QRBBRNNK"},
            { 738, "QRBBRNKN"},
            { 739, "QRKBRNNB"},
            { 740, "QRBKBRNN"},
            { 741, "QRNBRBNK"},
            { 742, "QRBNBRKN"},
            { 743, "QRKBRBNN"},
            { 744, "QBRKRNNB"},
            { 745, "BQRNRNBK"},
            { 746, "QBRNRNKB"},
            { 747, "BQKRRNBN"},
            { 748, "QRNKRNBB"},
            { 749, "QRBNRNBK"},
            { 750, "QRNBRNKB"},
            { 751, "QRKNRNBB"},
            { 752, "QRNKBRNB"},
            { 753, "QRNNRBBK"},
            { 754, "QRNNBRKB"},
            { 755, "QRKNRBBN"},
            { 756, "QBRKRBNN"},
            { 757, "BQRNBRNK"},
            { 758, "QBRNRBKN"},
            { 759, "BQKRBRNN"},
            { 760, "QRNKRBBN"},
            { 761, "QRBNBRNK"},
            { 762, "QRNBRBKN"},
            { 763, "QRKNBRNB"},
            { 764, "QRNKBBRN"},
            { 765, "QRNNBBRK"},
            { 766, "QRNNBBKR"},
            { 767, "QRKNBBRN"},
            { 768, "BBRKRNNQ"},
            { 769, "BBRQRNNK"},
            { 770, "BBRQRNKN"},
            { 771, "BBKRRNNQ"},
            { 772, "BRQKRNBN"},
            { 773, "RBBQRNNK"},
            { 774, "BRQBRNKN"},
            { 775, "RBKQRNNB"},
            { 776, "BRQKBRNN"},
            { 777, "RBQNRBNK"},
            { 778, "BRQNBRKN"},
            { 779, "RBKQRBNN"},
            { 780, "RBBKRNNQ"},
            { 781, "BRQBRNNK"},
            { 782, "RBBQRNKN"},
            { 783, "BRKBRNNQ"},
            { 784, "RQBKRNBN"},
            { 785, "RQBBRNNK"},
            { 786, "RQBBRNKN"},
            { 787, "RQKBRNNB"},
            { 788, "RQBKBRNN"},
            { 789, "RQNBRBNK"},
            { 790, "RQBNBRKN"},
            { 791, "RQKBRBNN"},
            { 792, "RBQKRNNB"},
            { 793, "BRQNRNBK"},
            { 794, "RBQNRNKB"},
            { 795, "BRKQRNBN"},
            { 796, "RQNKRNBB"},
            { 797, "RQBNRNBK"},
            { 798, "RQNBRNKB"},
            { 799, "RQKNRNBB"},
            { 800, "RQNKBRNB"},
            { 801, "RQNNRBBK"},
            { 802, "RQNNBRKB"},
            { 803, "RQKNRBBN"},
            { 804, "RBQKRBNN"},
            { 805, "BRQNBRNK"},
            { 806, "RBQNRBKN"},
            { 807, "BRKQBRNN"},
            { 808, "RQNKRBBN"},
            { 809, "RQBNBRNK"},
            { 810, "RQNBRBKN"},
            { 811, "RQKNBRNB"},
            { 812, "RQNKBBRN"},
            { 813, "RQNNBBRK"},
            { 814, "RQNNBBKR"},
            { 815, "RQKNBBRN"},
            { 816, "BBRKRNQN"},
            { 817, "BBRNRNQK"},
            { 818, "BBRNRNKQ"},
            { 819, "BBKRRNQN"},
            { 820, "BRNKRNBQ"},
            { 821, "RBBNRNQK"},
            { 822, "BRNBRNKQ"},
            { 823, "RBKNRNQB"},
            { 824, "BRNKBRNQ"},
            { 825, "RBNQRBNK"},
            { 826, "BRNQBRKN"},
            { 827, "RBKNRBNQ"},
            { 828, "RBBKRNQN"},
            { 829, "BRNBRNQK"},
            { 830, "RBBNRNKQ"},
            { 831, "BRKBRNQN"},
            { 832, "RNBKRNBQ"},
            { 833, "RNBBRNQK"},
            { 834, "RNBBRNKQ"},
            { 835, "RNKBRNQB"},
            { 836, "RNBKBRNQ"},
            { 837, "RNQBRBNK"},
            { 838, "RNBQBRKN"},
            { 839, "RNKBRBNQ"},
            { 840, "RBNKRNQB"},
            { 841, "BRNQRNBK"},
            { 842, "RBNQRNKB"},
            { 843, "BRKNRNBQ"},
            { 844, "RNQKRNBB"},
            { 845, "RNBQRNBK"},
            { 846, "RNQBRNKB"},
            { 847, "RNKQRNBB"},
            { 848, "RNQKBRNB"},
            { 849, "RNQNRBBK"},
            { 850, "RNQNBRKB"},
            { 851, "RNKQRBBN"},
            { 852, "RBNKRBNQ"},
            { 853, "BRNQBRNK"},
            { 854, "RBNQRBKN"},
            { 855, "BRKNBRNQ"},
            { 856, "RNQKRBBN"},
            { 857, "RNBQBRNK"},
            { 858, "RNQBRBKN"},
            { 859, "RNKQBRNB"},
            { 860, "RNQKBBRN"},
            { 861, "RNQNBBRK"},
            { 862, "RNQNBBKR"},
            { 863, "RNKQBBRN"},
            { 864, "BBRKRQNN"},
            { 865, "BBRNRQNK"},
            { 866, "BBRNRQKN"},
            { 867, "BBKRRQNN"},
            { 868, "BRNKRQBN"},
            { 869, "RBBNRQNK"},
            { 870, "BRNBRQKN"},
            { 871, "RBKNRQNB"},
            { 872, "BRNKBRQN"},
            { 873, "RBNNRBQK"},
            { 874, "BRNNBRKQ"},
            { 875, "RBKNRBQN"},
            { 876, "RBBKRQNN"},
            { 877, "BRNBRQNK"},
            { 878, "RBBNRQKN"},
            { 879, "BRKBRQNN"},
            { 880, "RNBKRQBN"},
            { 881, "RNBBRQNK"},
            { 882, "RNBBRQKN"},
            { 883, "RNKBRQNB"},
            { 884, "RNBKBRQN"},
            { 885, "RNNBRBQK"},
            { 886, "RNBNBRKQ"},
            { 887, "RNKBRBQN"},
            { 888, "RBNKRQNB"},
            { 889, "BRNNRQBK"},
            { 890, "RBNNRQKB"},
            { 891, "BRKNRQBN"},
            { 892, "RNNKRQBB"},
            { 893, "RNBNRQBK"},
            { 894, "RNNBRQKB"},
            { 895, "RNKNRQBB"},
            { 896, "RNNKBRQB"},
            { 897, "RNNQRBBK"},
            { 898, "RNNQBRKB"},
            { 899, "RNKNRBBQ"},
            { 900, "RBNKRBQN"},
            { 901, "BRNNBRQK"},
            { 902, "RBNNRBKQ"},
            { 903, "BRKNBRQN"},
            { 904, "RNNKRBBQ"},
            { 905, "RNBNBRQK"},
            { 906, "RNNBRBKQ"},
            { 907, "RNKNBRQB"},
            { 908, "RNNKBBRQ"},
            { 909, "RNNQBBRK"},
            { 910, "RNNQBBKR"},
            { 911, "RNKNBBRQ"},
            { 912, "BBRKQRNN"},
            { 913, "BBRNQRNK"},
            { 914, "BBRNQRKN"},
            { 915, "BBKRQRNN"},
            { 916, "BRNKQRBN"},
            { 917, "RBBNQRNK"},
            { 918, "BRNBQRKN"},
            { 919, "RBKNQRNB"},
            { 920, "BRNKBQRN"},
            { 921, "RBNNQBRK"},
            { 922, "BRNNBQKR"},
            { 923, "RBKNQBRN"},
            { 924, "RBBKQRNN"},
            { 925, "BRNBQRNK"},
            { 926, "RBBNQRKN"},
            { 927, "BRKBQRNN"},
            { 928, "RNBKQRBN"},
            { 929, "RNBBQRNK"},
            { 930, "RNBBQRKN"},
            { 931, "RNKBQRNB"},
            { 932, "RNBKBQRN"},
            { 933, "RNNBQBRK"},
            { 934, "RNBNBQKR"},
            { 935, "RNKBQBRN"},
            { 936, "RBNKQRNB"},
            { 937, "BRNNQRBK"},
            { 938, "RBNNQRKB"},
            { 939, "BRKNQRBN"},
            { 940, "RNNKQRBB"},
            { 941, "RNBNQRBK"},
            { 942, "RNNBQRKB"},
            { 943, "RNKNQRBB"},
            { 944, "RNNKBQRB"},
            { 945, "RNNRQBBK"},
            { 946, "RNNRBQKB"},
            { 947, "RNKNQBBR"},
            { 948, "RBNKQBRN"},
            { 949, "BRNNBQRK"},
            { 950, "RBNNQBKR"},
            { 951, "BRKNBQRN"},
            { 952, "RNNKQBBR"},
            { 953, "RNBNBQRK"},
            { 954, "RNNBQBKR"},
            { 955, "RNKNBQRB"},
            { 956, "RNNKBBQR"},
            { 957, "RNNRBBQK"},
            { 958, "RNNRBBKQ"},
            { 959, "RNKNBBQR"},
            { 960, "BBQKNRNR"},
            { 961, "BBQRNRNK"},
            { 962, "BBQRNRKN"},
            { 963, "BBKQNRNR"},
            { 964, "BQRKNRBN"},
            { 965, "QBBRNRNK"},
            { 966, "BQRBNRKN"},
            { 967, "QBKRNRNB"},
            { 968, "BQRKBNRN"},
            { 969, "QBRNNBRK"},
            { 970, "BQRNBNKR"},
            { 971, "QBKRNBRN"},
            { 972, "QBBKNRNR"},
            { 973, "BQRBNRNK"},
            { 974, "QBBRNRKN"},
            { 975, "BQKBNRNR"},
            { 976, "QRBKNRBN"},
            { 977, "QRBBNRNK"},
            { 978, "QRBBNRKN"},
            { 979, "QRKBNRNB"},
            { 980, "QRBKBNRN"},
            { 981, "QRNBNBRK"},
            { 982, "QRBNBNKR"},
            { 983, "QRKBNBRN"},
            { 984, "QBRKNRNB"},
            { 985, "BQRNNRBK"},
            { 986, "QBRNNRKB"},
            { 987, "BQKRNRBN"},
            { 988, "QRNKNRBB"},
            { 989, "QRBNNRBK"},
            { 990, "QRNBNRKB"},
            { 991, "QRKNNRBB"},
            { 992, "QRNKBNRB"},
            { 993, "QRNRNBBK"},
            { 994, "QRNRBNKB"},
            { 995, "QRKNNBBR"},
            { 996, "QBRKNBRN"},
            { 997, "BQRNBNRK"},
            { 998, "QBRNNBKR"},
            { 999, "BQKRBNRN"},
            { 1000, "QRNKNBBR"},
            { 1001, "QRBNBNRK"},
            { 1002, "QRNBNBKR"},
            { 1003, "QRKNBNRB"},
            { 1004, "QRNKBBNR"},
            { 1005, "QRNRBBNK"},
            { 1006, "QRNRBBKN"},
            { 1007, "QRKNBBNR"},
            { 1008, "BBRKNRNQ"},
            { 1009, "BBRQNRNK"},
            { 1010, "BBRQNRKN"},
            { 1011, "BBKRNRNQ"},
            { 1012, "BRQKNRBN"},
            { 1013, "RBBQNRNK"},
            { 1014, "BRQBNRKN"},
            { 1015, "RBKQNRNB"},
            { 1016, "BRQKBNRN"},
            { 1017, "RBQNNBRK"},
            { 1018, "BRQNBNKR"},
            { 1019, "RBKQNBRN"},
            { 1020, "RBBKNRNQ"},
            { 1021, "BRQBNRNK"},
            { 1022, "RBBQNRKN"},
            { 1023, "BRKBNRNQ"},
            { 1024, "RQBKNRBN"},
            { 1025, "RQBBNRNK"},
            { 1026, "RQBBNRKN"},
            { 1027, "RQKBNRNB"},
            { 1028, "RQBKBNRN"},
            { 1029, "RQNBNBRK"},
            { 1030, "RQBNBNKR"},
            { 1031, "RQKBNBRN"},
            { 1032, "RBQKNRNB"},
            { 1033, "BRQNNRBK"},
            { 1034, "RBQNNRKB"},
            { 1035, "BRKQNRBN"},
            { 1036, "RQNKNRBB"},
            { 1037, "RQBNNRBK"},
            { 1038, "RQNBNRKB"},
            { 1039, "RQKNNRBB"},
            { 1040, "RQNKBNRB"},
            { 1041, "RQNRNBBK"},
            { 1042, "RQNRBNKB"},
            { 1043, "RQKNNBBR"},
            { 1044, "RBQKNBRN"},
            { 1045, "BRQNBNRK"},
            { 1046, "RBQNNBKR"},
            { 1047, "BRKQBNRN"},
            { 1048, "RQNKNBBR"},
            { 1049, "RQBNBNRK"},
            { 1050, "RQNBNBKR"},
            { 1051, "RQKNBNRB"},
            { 1052, "RQNKBBNR"},
            { 1053, "RQNRBBNK"},
            { 1054, "RQNRBBKN"},
            { 1055, "RQKNBBNR"},
            { 1056, "BBRKNRQN"},
            { 1057, "BBRNNRQK"},
            { 1058, "BBRNNRKQ"},
            { 1059, "BBKRNRQN"},
            { 1060, "BRNKNRBQ"},
            { 1061, "RBBNNRQK"},
            { 1062, "BRNBNRKQ"},
            { 1063, "RBKNNRQB"},
            { 1064, "BRNKBNRQ"},
            { 1065, "RBNQNBRK"},
            { 1066, "BRNQBNKR"},
            { 1067, "RBKNNBRQ"},
            { 1068, "RBBKNRQN"},
            { 1069, "BRNBNRQK"},
            { 1070, "RBBNNRKQ"},
            { 1071, "BRKBNRQN"},
            { 1072, "RNBKNRBQ"},
            { 1073, "RNBBNRQK"},
            { 1074, "RNBBNRKQ"},
            { 1075, "RNKBNRQB"},
            { 1076, "RNBKBNRQ"},
            { 1077, "RNQBNBRK"},
            { 1078, "RNBQBNKR"},
            { 1079, "RNKBNBRQ"},
            { 1080, "RBNKNRQB"},
            { 1081, "BRNQNRBK"},
            { 1082, "RBNQNRKB"},
            { 1083, "BRKNNRBQ"},
            { 1084, "RNQKNRBB"},
            { 1085, "RNBQNRBK"},
            { 1086, "RNQBNRKB"},
            { 1087, "RNKQNRBB"},
            { 1088, "RNQKBNRB"},
            { 1089, "RNQRNBBK"},
            { 1090, "RNQRBNKB"},
            { 1091, "RNKQNBBR"},
            { 1092, "RBNKNBRQ"},
            { 1093, "BRNQBNRK"},
            { 1094, "RBNQNBKR"},
            { 1095, "BRKNBNRQ"},
            { 1096, "RNQKNBBR"},
            { 1097, "RNBQBNRK"},
            { 1098, "RNQBNBKR"},
            { 1099, "RNKQBNRB"},
            { 1100, "RNQKBBNR"},
            { 1101, "RNQRBBNK"},
            { 1102, "RNQRBBKN"},
            { 1103, "RNKQBBNR"},
            { 1104, "BBRKNQRN"},
            { 1105, "BBRNNQRK"},
            { 1106, "BBRNNQKR"},
            { 1107, "BBKRNQRN"},
            { 1108, "BRNKNQBR"},
            { 1109, "RBBNNQRK"},
            { 1110, "BRNBNQKR"},
            { 1111, "RBKNNQRB"},
            { 1112, "BRNKBNQR"},
            { 1113, "RBNRNBQK"},
            { 1114, "BRNRBNKQ"},
            { 1115, "RBKNNBQR"},
            { 1116, "RBBKNQRN"},
            { 1117, "BRNBNQRK"},
            { 1118, "RBBNNQKR"},
            { 1119, "BRKBNQRN"},
            { 1120, "RNBKNQBR"},
            { 1121, "RNBBNQRK"},
            { 1122, "RNBBNQKR"},
            { 1123, "RNKBNQRB"},
            { 1124, "RNBKBNQR"},
            { 1125, "RNRBNBQK"},
            { 1126, "RNBRBNKQ"},
            { 1127, "RNKBNBQR"},
            { 1128, "RBNKNQRB"},
            { 1129, "BRNRNQBK"},
            { 1130, "RBNRNQKB"},
            { 1131, "BRKNNQBR"},
            { 1132, "RNRKNQBB"},
            { 1133, "RNBRNQBK"},
            { 1134, "RNRBNQKB"},
            { 1135, "RNKRNQBB"},
            { 1136, "RNRKBNQB"},
            { 1137, "RNRQNBBK"},
            { 1138, "RNRQBNKB"},
            { 1139, "RNKRNBBQ"},
            { 1140, "RBNKNBQR"},
            { 1141, "BRNRBNQK"},
            { 1142, "RBNRNBKQ"},
            { 1143, "BRKNBNQR"},
            { 1144, "RNRKNBBQ"},
            { 1145, "RNBRBNQK"},
            { 1146, "RNRBNBKQ"},
            { 1147, "RNKRBNQB"},
            { 1148, "RNRKBBNQ"},
            { 1149, "RNRQBBNK"},
            { 1150, "RNRQBBKN"},
            { 1151, "RNKRBBNQ"},
            { 1152, "BBRKQNRN"},
            { 1153, "BBRNQNRK"},
            { 1154, "BBRNQNKR"},
            { 1155, "BBKRQNRN"},
            { 1156, "BRNKQNBR"},
            { 1157, "RBBNQNRK"},
            { 1158, "BRNBQNKR"},
            { 1159, "RBKNQNRB"},
            { 1160, "BRNKBQNR"},
            { 1161, "RBNRQBNK"},
            { 1162, "BRNRBQKN"},
            { 1163, "RBKNQBNR"},
            { 1164, "RBBKQNRN"},
            { 1165, "BRNBQNRK"},
            { 1166, "RBBNQNKR"},
            { 1167, "BRKBQNRN"},
            { 1168, "RNBKQNBR"},
            { 1169, "RNBBQNRK"},
            { 1170, "RNBBQNKR"},
            { 1171, "RNKBQNRB"},
            { 1172, "RNBKBQNR"},
            { 1173, "RNRBQBNK"},
            { 1174, "RNBRBQKN"},
            { 1175, "RNKBQBNR"},
            { 1176, "RBNKQNRB"},
            { 1177, "BRNRQNBK"},
            { 1178, "RBNRQNKB"},
            { 1179, "BRKNQNBR"},
            { 1180, "RNRKQNBB"},
            { 1181, "RNBRQNBK"},
            { 1182, "RNRBQNKB"},
            { 1183, "RNKRQNBB"},
            { 1184, "RNRKBQNB"},
            { 1185, "RNRNQBBK"},
            { 1186, "RNRNBQKB"},
            { 1187, "RNKRQBBN"},
            { 1188, "RBNKQBNR"},
            { 1189, "BRNRBQNK"},
            { 1190, "RBNRQBKN"},
            { 1191, "BRKNBQNR"},
            { 1192, "RNRKQBBN"},
            { 1193, "RNBRBQNK"},
            { 1194, "RNRBQBKN"},
            { 1195, "RNKRBQNB"},
            { 1196, "RNRKBBQN"},
            { 1197, "RNRNBBQK"},
            { 1198, "RNRNBBKQ"},
            { 1199, "RNKRBBQN"},
            { 1200, "BBQKNNRR"},
            { 1201, "BBQRNNRK"},
            { 1202, "BBQRNNKR"},
            { 1203, "BBKQNNRR"},
            { 1204, "BQRKNNBR"},
            { 1205, "QBBRNNRK"},
            { 1206, "BQRBNNKR"},
            { 1207, "QBKRNNRB"},
            { 1208, "BQRKBNNR"},
            { 1209, "QBRRNBNK"},
            { 1210, "BQRRBNKN"},
            { 1211, "QBKRNBNR"},
            { 1212, "QBBKNNRR"},
            { 1213, "BQRBNNRK"},
            { 1214, "QBBRNNKR"},
            { 1215, "BQKBNNRR"},
            { 1216, "QRBKNNBR"},
            { 1217, "QRBBNNRK"},
            { 1218, "QRBBNNKR"},
            { 1219, "QRKBNNRB"},
            { 1220, "QRBKBNNR"},
            { 1221, "QRRBNBNK"},
            { 1222, "QRBRBNKN"},
            { 1223, "QRKBNBNR"},
            { 1224, "QBRKNNRB"},
            { 1225, "BQRRNNBK"},
            { 1226, "QBRRNNKB"},
            { 1227, "BQKRNNBR"},
            { 1228, "QRRKNNBB"},
            { 1229, "QRBRNNBK"},
            { 1230, "QRRBNNKB"},
            { 1231, "QRKRNNBB"},
            { 1232, "QRRKBNNB"},
            { 1233, "QRRNNBBK"},
            { 1234, "QRRNBNKB"},
            { 1235, "QRKRNBBN"},
            { 1236, "QBRKNBNR"},
            { 1237, "BQRRBNNK"},
            { 1238, "QBRRNBKN"},
            { 1239, "BQKRBNNR"},
            { 1240, "QRRKNBBN"},
            { 1241, "QRBRBNNK"},
            { 1242, "QRRBNBKN"},
            { 1243, "QRKRBNNB"},
            { 1244, "QRRKBBNN"},
            { 1245, "QRRNBBNK"},
            { 1246, "QRRNBBKN"},
            { 1247, "QRKRBBNN"},
            { 1248, "BBRKNNRQ"},
            { 1249, "BBRQNNRK"},
            { 1250, "BBRQNNKR"},
            { 1251, "BBKRNNRQ"},
            { 1252, "BRQKNNBR"},
            { 1253, "RBBQNNRK"},
            { 1254, "BRQBNNKR"},
            { 1255, "RBKQNNRB"},
            { 1256, "BRQKBNNR"},
            { 1257, "RBQRNBNK"},
            { 1258, "BRQRBNKN"},
            { 1259, "RBKQNBNR"},
            { 1260, "RBBKNNRQ"},
            { 1261, "BRQBNNRK"},
            { 1262, "RBBQNNKR"},
            { 1263, "BRKBNNRQ"},
            { 1264, "RQBKNNBR"},
            { 1265, "RQBBNNRK"},
            { 1266, "RQBBNNKR"},
            { 1267, "RQKBNNRB"},
            { 1268, "RQBKBNNR"},
            { 1269, "RQRBNBNK"},
            { 1270, "RQBRBNKN"},
            { 1271, "RQKBNBNR"},
            { 1272, "RBQKNNRB"},
            { 1273, "BRQRNNBK"},
            { 1274, "RBQRNNKB"},
            { 1275, "BRKQNNBR"},
            { 1276, "RQRKNNBB"},
            { 1277, "RQBRNNBK"},
            { 1278, "RQRBNNKB"},
            { 1279, "RQKRNNBB"},
            { 1280, "RQRKBNNB"},
            { 1281, "RQRNNBBK"},
            { 1282, "RQRNBNKB"},
            { 1283, "RQKRNBBN"},
            { 1284, "RBQKNBNR"},
            { 1285, "BRQRBNNK"},
            { 1286, "RBQRNBKN"},
            { 1287, "BRKQBNNR"},
            { 1288, "RQRKNBBN"},
            { 1289, "RQBRBNNK"},
            { 1290, "RQRBNBKN"},
            { 1291, "RQKRBNNB"},
            { 1292, "RQRKBBNN"},
            { 1293, "RQRNBBNK"},
            { 1294, "RQRNBBKN"},
            { 1295, "RQKRBBNN"},
            { 1296, "BBRKNNQR"},
            { 1297, "BBRRNNQK"},
            { 1298, "BBRRNNKQ"},
            { 1299, "BBKRNNQR"},
            { 1300, "BRRKNNBQ"},
            { 1301, "RBBRNNQK"},
            { 1302, "BRRBNNKQ"},
            { 1303, "RBKRNNQB"},
            { 1304, "BRRKBNNQ"},
            { 1305, "RBRQNBNK"},
            { 1306, "BRRQBNKN"},
            { 1307, "RBKRNBNQ"},
            { 1308, "RBBKNNQR"},
            { 1309, "BRRBNNQK"},
            { 1310, "RBBRNNKQ"},
            { 1311, "BRKBNNQR"},
            { 1312, "RRBKNNBQ"},
            { 1313, "RRBBNNQK"},
            { 1314, "RRBBNNKQ"},
            { 1315, "RRKBNNQB"},
            { 1316, "RRBKBNNQ"},
            { 1317, "RRQBNBNK"},
            { 1318, "RRBQBNKN"},
            { 1319, "RRKBNBNQ"},
            { 1320, "RBRKNNQB"},
            { 1321, "BRRQNNBK"},
            { 1322, "RBRQNNKB"},
            { 1323, "BRKRNNBQ"},
            { 1324, "RRQKNNBB"},
            { 1325, "RRBQNNBK"},
            { 1326, "RRQBNNKB"},
            { 1327, "RRKQNNBB"},
            { 1328, "RRQKBNNB"},
            { 1329, "RRQNNBBK"},
            { 1330, "RRQNBNKB"},
            { 1331, "RRKQNBBN"},
            { 1332, "RBRKNBNQ"},
            { 1333, "BRRQBNNK"},
            { 1334, "RBRQNBKN"},
            { 1335, "BRKRBNNQ"},
            { 1336, "RRQKNBBN"},
            { 1337, "RRBQBNNK"},
            { 1338, "RRQBNBKN"},
            { 1339, "RRKQBNNB"},
            { 1340, "RRQKBBNN"},
            { 1341, "RRQNBBNK"},
            { 1342, "RRQNBBKN"},
            { 1343, "RRKQBBNN"},
            { 1344, "BBRKNQNR"},
            { 1345, "BBRRNQNK"},
            { 1346, "BBRRNQKN"},
            { 1347, "BBKRNQNR"},
            { 1348, "BRRKNQBN"},
            { 1349, "RBBRNQNK"},
            { 1350, "BRRBNQKN"},
            { 1351, "RBKRNQNB"},
            { 1352, "BRRKBNQN"},
            { 1353, "RBRNNBQK"},
            { 1354, "BRRNBNKQ"},
            { 1355, "RBKRNBQN"},
            { 1356, "RBBKNQNR"},
            { 1357, "BRRBNQNK"},
            { 1358, "RBBRNQKN"},
            { 1359, "BRKBNQNR"},
            { 1360, "RRBKNQBN"},
            { 1361, "RRBBNQNK"},
            { 1362, "RRBBNQKN"},
            { 1363, "RRKBNQNB"},
            { 1364, "RRBKBNQN"},
            { 1365, "RRNBNBQK"},
            { 1366, "RRBNBNKQ"},
            { 1367, "RRKBNBQN"},
            { 1368, "RBRKNQNB"},
            { 1369, "BRRNNQBK"},
            { 1370, "RBRNNQKB"},
            { 1371, "BRKRNQBN"},
            { 1372, "RRNKNQBB"},
            { 1373, "RRBNNQBK"},
            { 1374, "RRNBNQKB"},
            { 1375, "RRKNNQBB"},
            { 1376, "RRNKBNQB"},
            { 1377, "RRNQNBBK"},
            { 1378, "RRNQBNKB"},
            { 1379, "RRKNNBBQ"},
            { 1380, "RBRKNBQN"},
            { 1381, "BRRNBNQK"},
            { 1382, "RBRNNBKQ"},
            { 1383, "BRKRBNQN"},
            { 1384, "RRNKNBBQ"},
            { 1385, "RRBNBNQK"},
            { 1386, "RRNBNBKQ"},
            { 1387, "RRKNBNQB"},
            { 1388, "RRNKBBNQ"},
            { 1389, "RRNQBBNK"},
            { 1390, "RRNQBBKN"},
            { 1391, "RRKNBBNQ"},
            { 1392, "BBRKQNNR"},
            { 1393, "BBRRQNNK"},
            { 1394, "BBRRQNKN"},
            { 1395, "BBKRQNNR"},
            { 1396, "BRRKQNBN"},
            { 1397, "RBBRQNNK"},
            { 1398, "BRRBQNKN"},
            { 1399, "RBKRQNNB"},
            { 1400, "BRRKBQNN"},
            { 1401, "RBRNQBNK"},
            { 1402, "BRRNBQKN"},
            { 1403, "RBKRQBNN"},
            { 1404, "RBBKQNNR"},
            { 1405, "BRRBQNNK"},
            { 1406, "RBBRQNKN"},
            { 1407, "BRKBQNNR"},
            { 1408, "RRBKQNBN"},
            { 1409, "RRBBQNNK"},
            { 1410, "RRBBQNKN"},
            { 1411, "RRKBQNNB"},
            { 1412, "RRBKBQNN"},
            { 1413, "RRNBQBNK"},
            { 1414, "RRBNBQKN"},
            { 1415, "RRKBQBNN"},
            { 1416, "RBRKQNNB"},
            { 1417, "BRRNQNBK"},
            { 1418, "RBRNQNKB"},
            { 1419, "BRKRQNBN"},
            { 1420, "RRNKQNBB"},
            { 1421, "RRBNQNBK"},
            { 1422, "RRNBQNKB"},
            { 1423, "RRKNQNBB"},
            { 1424, "RRNKBQNB"},
            { 1425, "RRNNQBBK"},
            { 1426, "RRNNBQKB"},
            { 1427, "RRKNQBBN"},
            { 1428, "RBRKQBNN"},
            { 1429, "BRRNBQNK"},
            { 1430, "RBRNQBKN"},
            { 1431, "BRKRBQNN"},
            { 1432, "RRNKQBBN"},
            { 1433, "RRBNBQNK"},
            { 1434, "RRNBQBKN"},
            { 1435, "RRKNBQNB"},
            { 1436, "RRNKBBQN"},
            { 1437, "RRNNBBQK"},
            { 1438, "RRNNBBKQ"},
            { 1439, "RRKNBBQN"}
        };

        [Test]
        public static void TestSymmetrical()
        {
            foreach (KeyValuePair<int, string> position in startArrays)
            {
                string expected = string.Format("{0}/pppppppp/8/8/8/8/PPPPPPPP/{1} w KQkq - 0 1", position.Value.ToLower(), position.Value);
                Assert.AreEqual(expected, ChessUtilities.FenForChess960Symmetrical(position.Key));
            }
        }

        [Test]
        public static void TestAsymetrical()
        {
            Assert.AreEqual("bnqnrbkr/pppppppp/8/8/8/8/PPPPPPPP/QNBBNRKR w KQkq - 0 1", ChessUtilities.FenForChess960Asymmetrical(5, 18));
        }

        [Test]
        public static void TestHorde()
        {
            Assert.AreEqual("rbbqnknr/pppppppp/8/1PP2PP1/PPPPPPPP/PPPPPPPP/PPPPPPPP/PPPPPPPP w kq - 0 1", ChessUtilities.FenForHorde960(500));
        }

        [Test]
        public static void TestRacingKingsSymmetrical()
        {
            foreach (KeyValuePair<int, string> position in racingKingsStartArrays)
            {
                string whiteRowOne = position.Value.Substring(0, 4);
                string whiteRowTwo = position.Value.Substring(4, 4);
                string blackRowOne = string.Concat(whiteRowOne.ToLowerInvariant().Reverse());
                string blackRowTwo = string.Concat(whiteRowTwo.ToLowerInvariant().Reverse());
                Assert.AreEqual(string.Format("8/8/8/8/8/8/{0}{1}/{2}{3} w - - 0 1", blackRowOne, whiteRowOne, blackRowTwo, whiteRowTwo), ChessUtilities.FenForRacingKings1440Symmetrical(position.Key));
            }
        }

        [Test]
        public static void TestRacingKingsAsymmetrical()
        {
            Assert.AreEqual("8/8/8/8/8/8/rkbbRBRN/rnnqQBKN w - - 0 1", ChessUtilities.FenForRacingKings1440Asymmetrical(1430, 1395));
        }
    }
}
